Ensembl/ensembl-production

modules/Bio/EnsEMBL/Production/Pipeline/GTF/DumpFile.pm
To enable eg! FTP pipeline to use the e! GTF dumper module.
=> Skipping gtf_to_genepred & gene_pred_check, getting version & directory path for eg!

scripts/ontology/scripts/compute_closure.pl
This change moves the requirement for the 2 terms to be part of the same ontology rather than the same namespace/aspect. The means that it is able to capture closures where a term in "molecular_function" is "part_of" a "biological process". See the GO terms GO:0061727, GO:0051596, GO:0019243 and GO:0019172
=> Update compute_closure.pl to allow cross aspect relationships

modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
Regular expression changes to cater for filename consistency when turning on per_chromosome flag
=> Regular expression changes to cater for filename consistency

scripts/ontology/scripts/compute_closure.pl
Modified the inter ontology import for retrieving parents of a child term to restrict it to is_a and part_of. In cases where there are more relationships that just the basic 2 this causes querying issues in the marts. For example querying with GO:0008233 would get features annotated with GO:0007866 as well
=> Inter aspect closures to map over is_a and part_of

scripts/ontology/scripts/load_OBO_file.pl
Stripped out colons from the slim names so that when the map tables are generated they do not include the colon, but are instead replaced with a more db friendly underscore.
=> Strip colon from slim names

modules/Bio/EnsEMBL/Production/Pipeline/GeneTreeHighlight/HighlightGO.pm, modules/Bio/EnsEMBL/Production/Pipeline/GeneTreeHighlight/HighlightInterPro.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneTreeHighlighting_conf.pm
For VectorBase the compara db has 'vb' instead of a division; the modules were deriving the division from the core dbs, which have 'metazoa' set instead. So I added the ability to specify it as a parameter. (It seems like this functionality would also be required to run the pipeline on the 'pan_homology' db too, but I didn't test that.)
Also, I noticed that a capacity parameter was provided in the config, but never applied, so I added that.
Unfortunately my editor has removed trailing whitespace without me realising; so that's muddied the waters of the commit. Let me know if you want a fresh commit without those changes.
=> Adding ability to specify compara division for gene tree highlighting

scripts/datafiles/check_datafiles.pl
Data files should be group-writable and the group set to "ensemblftp" (hence this is the new default for group checks).  Actual ownership should be irrelevant as long as these permissions and group are maintained.
=> Updates to datafiles policy after EBI move

modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
Improves the number of mapped miRNA GOs to 781 for human rather than 10
=> for RNACentral, use precursor_rna rather than accession

modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
This is necessary in order to be able to migrate the RDF dump pipeline to using the ensembl-io framework. The ensembl-io based RDF writer needs to be able to access type information of the different 'features' so that it can format and print the appropriate record.
=> Towards and ensembl-io based RDF dump pipeline. Include type information for BulkFetcher derived 'features'.

scripts/sql2html.pl
Indices of this table were not parsed:
```sql
CREATE TABLE exon_boundaries (
gene_member_id   INT(10) UNSIGNED NOT NULL,
seq_member_id    INT(10) UNSIGNED NOT NULL,
dnafrag_start    INT NOT NULL,
dnafrag_end      INT NOT NULL,
sequence_length  INT(10) UNSIGNED NOT NULL,
left_over        TINYINT(1) DEFAULT 0 NOT NULL,
INDEX (seq_member_id),
INDEX (gene_member_id)
) ENGINE=MyISAM;
```
=> bugfix: allow "INDEX (column_name)" indices

modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
Please, this MUST be merged since the ensembl-io RDF code relies on the new interface.
=> [ENSCORESW-1928]. Use simplified and more generic interface.

modules/t/fake_ebeye_binaries/xmllint
Missing binary was causing Travis to fail
Local runs would work because the actual xmllint binary is usually on the path
With the added fake binary, Travis now passes successfully
=> add xmllint fake binary

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbAwareSpeciesFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FactoryTest_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Database-level operations have been moved from SpeciesFactory to a new parent module, DBFactory.
SpeciesFactory inherits that code, so functions in exactly the same way as previously. However, if your pipeline needs DB-level operations you can use DBFactory directly, and then flow to DbAwareSpeciesFactory, which has almost* the same behaviour as SpeciesFactory, but does not parse the registry, since DBFactory has done that and passed along the necessary data. (* The 'almost' is because DbAwareSpeciesFactory does not flow compara dbs down pipe #5; that behaviour makes no sense, now that DBFactory flows compara dbs down pipe #5.)
Some of the code has been refactored alongside this development, chiefly: the processing of taxonomic parameters has been simplfied; a couple of simple functions …
=> Making SpeciesFactory 'DB-aware'.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TranscriptomeDomains_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/GenerateSolr.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScan.pm
VectorBase use a pipeline to annotate protein domains on transcriptomes (for those at EBI, this pipeline is described in confluence: https://www.ebi.ac.uk/seqdb/confluence/display/EnsGen/Transcriptome+Domains+Pipeline). All of the modules for this pipeline are already in the ProteinFeatures directory in this repo, so it makes sense to also put the configuration there - although the use case is currently only for VectorBase, the code is generic, and will annotate domains on an arbitrary file of DNA sequences.
A couple of minor changes were required to existing modules, nothing controversial, I hope.
=> Pipeline config for transcriptome annotation

modules/Bio/EnsEMBL/Production/Pipeline/JSON/JsonRemodeller.pm, modules/t/housekeeping_apache2.t
Pushing to a scalar is classed as experimental in Perl 5.24 . It was probably an accident in this instance.
=> Remove scalar push

.travis.yml
In anticipation of standardising on 1.6.924, production can now test on the newest safe version of BioPerl. 1.7.2 currently blocked by a codon issue https://github.com/bioperl/bioperl-live/issues/266
=> Replace Bioperl 1.2.3 with 1.6.924 in test environment

modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/StoreGoXrefs.pm
spurious version=0 set silently by the API causes problems with duplicates.
=> enforce null version, no matter what the API tries to do

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Remove UCSC source from xref pipeline
There is currently an issue when mapping UCSC xrefs to Ensembl so it is safer to leave the source out altogether
=> remove UCSC source

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/DownloadSource.pm
Apologies for yet another change.
I noticed some jobs die with MEMLIMIT when downloading files, but not always. It is usually fine but if the resource is busy, the download takes longer and this exposes a problem with a memory leak in the code.
The memory leak is fixed by preparing the statements once the files have been downloaded rather than before, meaning they do not stay open while waiting for the download.
This should make the pipeline more robust to race conditions and busy resources
=> ENSCORESW-2793: reduce memory consumption

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/CoordinateMapping.pm
This patch is to skip the coordinate_mapping stage. This is normally run on the UCSC data loaded at the parsing stage. Because there are some issues with the UCSC data, we have removed it from the list of sources, which means there is no data in the database. The code checks for its existence though, so we skip the coordinate_mapping stage altogether to avoid the problem.
Once we have decided what we want to do with the UCSC data in the future, we will provide a cleaner solution, but this will allow the pipeline to run for release 94
=> ignore coordinate_checksum as no UCSC is loaded

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/sql/table.sql
This is so that the xref pipeline no longer depends on the
VersioningService repository for a single file. See
https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-2728 .
The imported file is the latest available version as of 2018-08-02:
VersioningService commit 6377671892cf897b70fb1a6603dc4ee398818a58 ,
sha256sum ee6a7335fa3835895b721e4b6a1926b4d7db04f645cec8eed5dd59443191b834 .
For the time being the original is still present in VersioningService
but its use is deprecated, it will be removed at some point in the near
future.
Note: this file needs a copyright update but either leave it until after
the version in VersioningService has been removed or update it in both
repos.
=> Xrefs: Import the versioning schema from VersioningService

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_vertebrates_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleSource.pm
Created a new vertebrate-specific config file, to keep the main one generic and more easily used by other divisions. Sundry minor fixes for issues that arose when I ran the pipeline for release 94.
=> Tweaks to xref pipeline config

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/CoordinateMapping.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion;
- Review the [contributing guidelines](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#why-could-my-pull-request-be-rejected) for this repository; remember in particular:
- if you change the schema you must patch the test databases as well, see [Updating the schema](https://github.com/Ensembl/ensembl/blob/release/90/CONTRIBUTING.md#updating-the-schema)
UCSC xrefs have been switched back on …
=> ENSCORESW-2792: re-instate UCSC xrefs

scripts/sql2html.pl
A vector format like SVG is generally more useful for this sort of data because it allows zooming in and out without loss of readability. This is important given how large some of our schema diagrams are. SVG files are also more space-efficient thank PNG ones, at least for the sort of resolutions GraphViz uses to produce the latter to make them readable anyway. On the other hand, the advantage of SVG over _e.g._ PDF is that it is natively supported as an image format by most Web browser _and_ can be directly exported to by GraphViz.
The format of diagram is controlled by a command-line option so it *is* still possible to generate PNGs should one choose to do so.
Please note that this PR introduces a dependency on ImageMagick (or GraphicsMagick with compatibility symlinks) because it uses …
=> sql2html: support generation of schema diagrams as SVGs

modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm
@james-monkeyshines changed this in the DbFactory a while ago: https://github.com/Ensembl/ensembl-production/commit/982ae326312297bf4773842945c51ddf8271157a#diff-408bb2c17c2990106fde7c1b32281f60L113
This broke this line here in the speciesFactory: https://github.com/Ensembl/ensembl-production/blob/release/94/modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm#L134
James fixed it on master but the change was not replicated to the release/94 branch. As a result the FTP checker pipeline is broken because it's using the compara flow. 
This change fix the broken compara flow by bringing James fix to release/94 branch
=> Reflect change in hash structure of compara dbs in parent module

modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsEBeye.pm
Passing $self instead of the input filename cuases the reformat_variants method to try to load a file on disk that does not exist and in turn causes the ReformatVariantsEBeye runnable to fail.
=> The reformat_variants method does not expect $self argument

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FactoryTest_conf.pm
For non-core groups, use the DNA db if it is necessary to do a division filter, and only spawn jobs down flow #2
=> Better handling of non-core dbs with DbFactory

modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
It produces a warning to not do this. Disconnecting is irrelevant to the results of this script, but the warning confused me when I had a problem.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::mysql::db handle database=information_schema;host=mysql-ps-staging-2.ebi.ac.uk;port=4467 at /nfs/production/panda/ensemblgenomes/wormbase/software/packages/ensembl/branches/branch-94/ensembl-hive/modules/Bio/EnsEMBL/Hive/Process.pm line 150.
=> Explicitly disconnect $dbh

modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
The recent merge in ensembl-io of pull request https://github.com/Ensembl/ensembl-io/pull/68
brings the RDF code and all the updates of the unified-design branch into the master branch.
Included in the updated is the removal of the SequenceOntologyMapper dependency in the BulkFetcherFeature.
This pull request updates production BulkFetcherFeature calls to remove the now unnecessary SequenceOntologyMapper dependency.
=> Remove SequenceOntologyMapper dependency

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
Currently it relies on being run by a worker that has been called with the -reg_conf parameter. This change is required by the pipeline that runs datachecks.
=> Add the ability to explicitly pass a registry file to DbFactory

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScan.pm
Use /scratch rather than /tmp space, as now recommended by TSC, for reasons of stability. This will hopefully fix the small numbers of intermittent and non-repeatable failures we get with every pipeline run (Bug report: ENSPROD-2607).
=> Use /scratch rather than /tmp space in Protein Features pipeline

modules/Bio/EnsEMBL/Production/Pipeline/OntologiesLoad/MartLoad.pm
Update /tmp to /scratch as recommended by System...
See ticket https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-2755 …
=> Replaced /tmp with /scratch

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScan.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/StoreProteinFeatures.pm
Currently, after running the protein features pipeline, you need to run a set of healthchecks. Equivalent datachecks now exist, and they can be integrated into the pipeline.
The pipeline runs the 'protein_features' group, plus the ForeignKeys datacheck.
(I've also included a couple of minor fixes, for handling jobs that run out of memory, and avoiding spurious warnings.)
Don't have to do checks as a separate step; it tends not to get forgotten, but integrating the datachecks is efficient, alerts you to problems earlier, and should make it a bit easier to re-run a subset of jobs if necessary.
Pipeline is a bit less 'fire and forget', perhaps; needs to be monitored for datacheck failures, but while running we're usually keeping an eye on the pipeline anyway.
There are no unit tests for the …
=> Adding module for datachecks to protein features pipeline

scripts/sql2html.pl
When doing some tests for the Compara documentation, I found that there was a .dot file around. I believe it shouldn't be there.
_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._
No leftover .dot file hanging around. Unlikely to go and pollute public-plugins
If people want the .dot file they have to go and uncomment the line in the source code
- [ no ] Have you added/modified unit tests to test the changes?
- [ no ] Have you run the entire test suite and no regression was detected?
- [ hopefully ] TravisCI passed on your branch
Dependencies
------------
None
=> fix: do not leave temporary dot files around

.travis.yml, travisci/harness.sh
Updated Bioperl version and fixing PERL5LIB export
Travis is broken on the repo as it can't install Bio::DB::HTS. …
=> Fixing bioperl version to stop problem installing HTS

.travis.yml
Travis is failing because it's using new code on ensembl master associated with release/97 production database …
=> switch clone branch to release/96

modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
If the division parameter is not defined then the pipeline will run and not dump anything.
Making this param …
=> Division is always required

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Make genome stats module run after the modules on which it relies for summary data.
Accurate statistics
Not aware of any
No unit tests, but test pipelines run and results checked.
=> Rejig structure of Variation Stats pipeline

modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
Extending regex that matches protein accessions to include hyphens.
Needed for successful import of plant species.
Pipeline won't fail...
Pipeline with this fix ran successfully.
=> Extending regex that matches protein accessions to include hyphens

modules/Bio/EnsEMBL/Production/Pipeline/Production/SnpDensity.pm
Modify SQL for calculating SNP density, to account for indels.
Indels are represented in the variation_feature table with seq_region_start > seq_region_end. The SQL in the density calculations assumed seq_region_start <= seq_region_end. This is only a problem if one boundary of the block within which the calculation are done falls exactly between the start and end of the  indel. That happens twice in the human 96 database, which means that two SNPs are not included in the density totals.
These 2 missing SNPs are not an issue for web display, because they're a drop in the ocean. But the datacheck I've just written isn't happy about the discrepancy... (The old healthcheck for this functionality arbitrarily allowed a discrepancy of up to 1000 before failing.)
Marginally more accurate density …
=> Account for indel variation features with seq_region_start > seq_region_end

sql/patch_96_97_a.sql
Bug fix, version number hadn't been updated in sql patch for production db.
=> Old version number used in sql patch

modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckComparaFtp.pm
Compara phyloxml files now have ID ranges embedded in the file names. Need to adjust the pattern for matching in the FTP Checker pipeline.
=> Compara file names changed, update string to match

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
As jobs for mapping analyses accumulate, they start to get in each other's way, since they are trying to access the same database tables, and at a critical mass average runtime increases for a while, before dropping down again as jobs complete.
Reduce unnecessary database load.
Not aware of any.
Pipeline not run with these settings, because to properly test would require a complete run of the pipeline, with seems a bit much. Config file initialises fine.
=> Adding analysis_capacity values for mapping modules.

modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Some variation databases are now empty since the data is coming from a VCF file. Our pipeline cannot deal with …
=> Handle empty variation db

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Phibase identifier were loaded after closure computation. Need to change
Closure table don't include PHI base …
=> Added PHI base ontology loading step (skip_phi parameter to skip)

modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Reverts Ensembl/ensembl-production#275.
Found issues when copying between mysql-ens-meta-prod-1 and mysql-ens-sta-1. I don't know what is going on but need to investigate further
=> Revert "Updated rsync command to use ciphers when copying over ssh. The rsync …"

modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm, modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
- increased mx_packet_size to 512Mb
- changed DbDumpingFactory to accept isGrch37 flag
-
Added GRch37 dedicated FTP …
=> Updated configuration for mysql dumps:

modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm, modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckFtp.pm
The VEP dumps used to be in `/vep` for non-vert and `/variation/VEP` for vert. There was a hack in place to work …
=> Removing old VEP dumps hack now that we have a unified FTP layout

modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlatIndexer.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
The Web team only have BLAT servers for 16 species and human GRCh37. Generating these files for all the species is …
=> Blat update

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Datachecks were being run on the variation dbs, not the core dbs. Need to override the 'variation' group that is being propagated from the SpeciesFactory.
Datachecks get run, rather than skipped.
None.
Test pipeline run successfully.
=> Fix datachecks for variation statistics pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Lates_calcarifer should not be in the BLAT list since Web does not need it.
We don't need to generate BLAT files …
=> lates_calcarifer should not be in the BLAT list

modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
There is code that in the ensembl-io repo that is intended to deal with this gracefully; it looks like it should work, but  providing an ontology adaptor caused it to generate empty GFF3 files.
=> GFF3 serializer does not require an ontology adaptor any more

scripts/update_mapping_set.pl
The regex was not generating a valid name for the previous release's database; so the script did not think it needed to do any mapping, because it's logic told it that it had a database for a brand new species.
=> Get correct name for previous release database

scripts/apply_patches.pl
Have the schema patcher look for ontology patches in _ensembl-ontology-schema_ rather than _ols-ensembl-loader_.
During a recent discussion regarding the patching of test databases in _ensembl-rest_ it has been decided to hand the ontology schema from Production back to Infrastructure because said schema is much more closely tied with Core code than with OLS.
Production will not have to patch test databases in _ensembl-rest_ every release.
None.
Dependencies
------------
=> apply_patches.pl: Update location of ontology schema

.travis.yml, modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/MySQLDumpsCheck.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm, modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
Added a new module to the MySQL dumping pipeline to make sure that we have a MySQL dump for each table of a …
=> Mysql dumps check 98

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
Changed farm queue name to rh74
rh7 queue are fewer now.
None
_If applicable, describe any possible undesirable …
=> Fixed typo on expected job queue rh7 -> rh74

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
The parameters in the prod db and pipeline config are currently out of sync. But pipeline config parameters have precedence, and override the prod db values, which is not what we want.
Consistent descriptions across core dbs, maintained centrally in prod db.
None
=> It's best if the analysis_description fields always come from the prod db

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Small fix, the datachecks run over core databases, but need to access variation data, so need a registry defined to find the variation db.
=> Pass registry with pre-existing parameter name

modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Escape \n characters from dump
MySQL dumps
no carriage return in the middle of the dumps
May slow down the dump …
=> Fixed mysql dump .. -raw parameter for \n characters.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Remove resource requirement for 4 cores - unnecessary, and makes it harder to get high-mem nodes. Bump up the sequence dumping capacity, tweak the Blast indexing (to enable jobs to start in good time), add capacity for RDF modules (otherwise it runs amok and eats all the db connections.
=> FTP Dump config tweaks

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Need to dump DNA if there is a geneset update as well as in the case of assembly updates. This is because repeat annotation is re-done, so even though the DNA might not be changing, the softmaksing is. (This implicitly affects the BLAST dumps, because these masked files are used there.)
Softmasked FASTA DNA files, and therefore BLAST results, will be using the most recent repeat annotations.
Possible wasted computation if a geneset is updated, but repeat annotation is not (this may sometimes be the case with non-vertebrates). But having more complicated logic is too not warranted, because updated genesets for existing assemblies is relatively rare for non-verts, so shouldn't be an issue in practice.
No unit tests, but test pipeline looks OK.
=> Need to dump DNA if there is a geneset update

modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileMetadata.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
Many non-vertebrates do not have Entrez or RefSeq xrefs. In these cases, TSVs files are created with just a header line, which is confusing for users, and looks like something might have gone wrong with the dump. (This logic also applies to UniProt, but I think everything should have those anyway.)
A similar issue exists with ENA xrefs, which are generally available for non-vertebrates but not vertebrates.
And there was a bug in the karyotype dumping, which meant that empty files were created for that data.
https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-4297
Remove uninformative files, hopefully reduce confusion.
Any existing scripts may always assume the presence of a file. But there are probably very few (if any) such scripts in use, and they can be easily fixed. The README now states …
=> Prevent creation of tsv files if there is no data.

sql/patch_98_99_b.sql, sql/table.sql
The XrefCategories HC (https://github.com/Ensembl/ensj-healthcheck/blob/release/98/src/org/ensembl/healthcheck/testcase/generic/XrefCategories.java) is making sure that external_db.type is not null but the schema allow null by default: https://github.com/Ensembl/ensembl-production/blob/release/98/sql/table.sql#L198
Update controlled table 
Get rid of an obsolete HC
None
Dependencies
------------
=> External DB Type now not null field

modules/Bio/EnsEMBL/Production/Pipeline/FASTA/ConcatFiles.pm
Add EOL anchor to the regex removing '.gz' from the gunzipped file name.
When processing file names containing …
=> Fix FASTA::ConcatFiles bgzip regex

modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeEBeye.pm, modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsEBeye.pm
Prefixing ebeye dumps to reduce Web team post handover work. This is to remove last step of this Web team ticket: …
=> Prefixing ebeye dumps to reduce Web team post handover work

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
It wasn't quite working right for core-like dbs, it was making invalid assumptions about the meta_keys in those db_types.
Using the module to iterate over corelike databases was raising an error, when everything was actually fine.
DbFactory handles corelike databases properly.
None spring to mind.
No unit tests for this module, but checked with test pipelines.
=> Slight change to the logic of the DbFactory

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Update JGI data source to internal ftp copy.
See https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3347
We will now not depend on external download of a static file, that has become inaccessible and will need a login (which will require code changes to make it work) 
If/when the data source files from JGI change, we will need to get a copy into our FTP server.
We would need to update the url anyways, so it's not much of an extra burden. 
no
Dependencies
------------
=> [ENSCORESW-3347] update JGI data source

conf/xref_LOD_mapping.json, conf/xref_LOD_schema.json, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Make DumpCore_conf.pm use a local copy of xref_LOD_mapping.json
The file in question used to come from VersioningService, which repository is now being phased out.
Do not depend on a deprecated repository. Indeed, reduce the number of external dependencies by one.
* A new top-level directory _conf_ has been created to hold the file in question.
* The schema of xref_LOD_mapping.json conforms to JSON Schema draft-07 rather than the current draft/2019-09 (draft-08 in the old nomenclature) due to the fact the validation tools I know do not support the latter yet.
Dependencies
------------
Should make the whole ensembl-production no longer depend on VersioningService.
=> DumpCore_conf.pm: use a local copy of xref_LOD_mapping.json

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Protein features pipeline was failing for a handful of jobs. It seems like super-long protein sequences were causing the Panther analysis to gobble up memory - but the failure was only sporadically registered as a memory issue, so wasn't always picked up by hive's MEMLIMIT detection. And in any case, the "high_mem" analysis was not high enough.
Pipeline should run without manual intervention, and should no longer be an assault on Marc's sanity.
Nothing that I can think of...
=> Protein feature memory

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
As descriibed in https://www.ebi.ac.uk/panda/jira/browse/ENSINT-412
Remove xrefs which do not link out to external …
=> removed aniseed xref for ciona from xrefsources json

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Enable dumping pipeline to store datacheck output.
Better able to debug failures.
None.
=> Enable dumping pipeline to store datacheck output

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm, modules/Bio/EnsEMBL/Production/Utils/ProductionDbUpdater.pm
One of the analysis_description datachecks is advisory, so do not want the pipeline to fail if it fails. Instead, have a separate datacheck run, and report any failures via email. Also, take advantage of new datacheck group for analysis_descriptions.
Also included is a bug fix for the controlled table update, to explicitly deal with undef values, so as to distinguish between empty strings and NULLs in the database (which is necessary when determining if the data has changed).
Advisory datacheck failures don't cause the pipeline to fail.
None
Test pipelines run.
=> Prod db sync pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/BulkSQL_conf.pm
Optionally run datacheck(s) after executing SQL on databases.
Sometimes we want to apply SQL statements to databases on the staging servers; it's handy to be able to subsequently run datachecks, to confirm that we've not broken anything, within the same pipeline.
More easily identify if SQL statements a) fix what they are supposed to be fixing, b) don't break anything.
Not aware of anything.
No unit tests, ran pipeline with datachecks when updating funcgen web_data with SQL, all worked fine.
=> Add the ability to run datachecks as part of the bulk SQL pipeline.

modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
Add disconnectt_when_idle command for RDF dumping, which was losing the DB connection because it spends so long generating vast amounts of data...
RDF dump jobs were failing after running for hours, due to a lost DB connection.
Jobs don't fail!
None I'm aware of.
Tested on dumps for release 100 - half a dozen failures without the fix, none after it. (Could be coincidence, of course, but hard to fully test without significant effort.)
=> Fix for RDF dumping losing connection

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FactoryTest_conf.pm
Add parameter to allow dbnames to be passed to DbFactory (and SpeciesFacory, since that inherits from it).
The use case that prompted this is for datachecks, to make it easier to run across a single collection db (or a subset of them); but it might also be useful for other pipelines.
Increased options for using module.
None I'm aware of.
Created instances of the FactoryTest pipeline to check that new and existing species/db-selection parameters worked as expected. Also tested in the ensembl-datacheck pipeline, DbDataChecks pipeline.
=> Add parameter to allow dbnames to be passed to DbFactory

modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/GeneNamesProjection.pm
Instead of the numeric accession for a gene name (e.g. 'HGNC:xxx'), the projection pipeline was loading the display name into the xref.dbprimary_acc column, aka the DBEntry->primary_id. This  means that linkout urls to the source database are broken, but is (almost annoyingly) easy to fix...
This is a fix for a known bug (ENSINT-438).
Linkout urls work correctly.
Not aware of any.
Toy pipeline tested with updated module.
=> Fix non-numeric gene name accessions

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
Datachecks are most efficient when they are run at the database level, rather than the species level. This only makes a big difference for collection databases. It can save quite a lot of time, because some datachecks have the 'per_db' flag set, meaning that they only need to be run once, regardless of how many species there are in the database.
In the GPAD load pipeline, the datachecks were run following a SpeciesFactory, so all datachecks were being run for every species. This has two consequences: 1) it's wasteful, because some complicated/long-running datachecks (e.g. ForeignKeys) are run unnecessarily, and 2) spurious errors can occur, because the datachecks are potentially being run for some species while db updates are occuring for other species, and failures can appear due to …
=> Run GPAD pipeline datachecks at database-level

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SampleData_vertebrates_conf.pm
Add `SampleData_vertebrates_conf` for specific configuration of Sample Data Pipeline for Vertebrates. In particular …
=> Add SampleData_vertebrates_conf

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
The datacheck email notification module assumes that the pipeline_name will be available, in order to be displayed in the subject line (https://github.com/Ensembl/ensembl-datacheck/pull/239).
Modification to datacheck repo's EmailNotify module will work as intended.
None.
=> pipeline_name parameter for datacheck notification

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/sars_cov_2_sources.json
List of sources used for sars_cov_2 xref …
=> list of xref sources used for sars_cov_2 annotation

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm, modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckVariationFtp.pm, modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm, modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpGenesJson.pm, modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpGenomeJson.pm, scripts/datafiles/build_datafile_ftp_directory.pl, scripts/datafiles/check_datafiles.pl, scripts/datafiles/sizes.pl
See ENSWEB-5706 and related tickets for more information. The REST server sees all MySQL servers (Vertebrates and non-Vertebrates), which contain in total two ancestral databases, but the current Registry model only allows one. The Compara API then fails because it is not able to access the other one
I am proposing to register the ancestral databases with their division name, preventing a clash between the Plants and Vertebrates databases. The change is being made in the Core repository, and ensembl-production has to be updated because several modules compare the registry name to "Ancestral sequences", which will now be "Plants Ancestral sequences" for Plants.
Two questions:
1. Do you still maintain this branch (`release/100`) ? I can make the PR onto `release/101` instead
2. Do you have …
=> [ENSCOMPARASW-3527] Allow division-prefixed Ancestral sequences Registry entries

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
We missed a problem with an update to the biotype table which was not reflected in the gene and transcript tables. There's already a datacheck for that, but we weren't using it - now we are.
Catch errors immediately.
None.
=> Add biotype datacheck to prod db sync pipeline.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Fix for : failed: ParamError: Cannot evaluate the expression: 'expr(#ontology_name# eq PR)expr' ==> '$self->_param_possibly_overridden('ontology_name', $overriding_hash) eq PR' Bareword "PR" not allowed while "strict subs" in use at (eval 78) line 1.
=> Bareword "PR" not allowed while "strict subs" in use at

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm
Multiple xref-related pipelines were using the same 'xref' datacheck group - some of these are specific to the work of a particular pipeline, so running them in another pipeline is redundant and potentially confusing.
Pipelines only run relevant datachecks.
None I can think of.
None done, but this is a very simple update.
=> Use datacheck groups relevant to the pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
The xref pipeline runs multiple mapping …
=> ENSCORESW-3263: run mapping sequentially for same species

scripts/py/dcparse.py, scripts/py/dcstat.py
Python 3.7+
Console Python script for parsing and reporting data from a Datacheck JSON report.
In many cases DCs generate lots of failures, some of them might not be relevant. This scripts help filtering out the not relevant ones and potentially add more complex criteria.
=> Add dcstat script for parsing DC JSON results

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScanVersionCheck.pm
Check if version of InterProScan service matches that of the command line program.
If the command line version is different to that of the lookup service, then the service cannot be used, and the program will do all computation locally. This is extremely time-consuming, so we generally don't want to do that - these changes make the pipeline fail if there is a mismatch, by default.
Occasionally, you may want to force the local computation to happen anyway, which can be done by setting `-skip_checksum_loading`. If that is true, then the service version check is not done.
Do not silently fall back to local computation, and then wonder why the lookups are taking so long.
Not aware of any.
Module tested in isolation; sample pipeline initialised and first job run. Works as expected.
=> Check if version of InterProScan service matches that of the command line program.

scripts/sync/publish_db.sh
Permission-granting script was not updating the new '-hh' server; added the appropriate shortcut, and updated the script to apply SQL there too.
Script works as intended for release 101.
=> Add HH version of eg-publicsql to grant script

modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm, modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/CreateFamilies.pm
The compara families pipeline wasn't populating some fields in the compara db - I don't think this causes anything to break, at the minute, but there might be future problems, because expected data is missing. And the datachecks fail, creating unnecessary noise.
Compara data is more complete, datachecks pass.
None.
=> Compara families pipeline wasn't populating some fields in the compara db

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Alignment.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Base.pm
disconnect_if_idle is implemented on the xref database during the alignment stage
The align jobs are mostly IO and …
=> ENSCORESW-3534: enable disconnect_if_idle for alignment jobs

modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DataChecksNonCore_conf.pm
When a non-core database (core-like, compara, funcgen, variation) is handed over, we run datachecks to check if it is correctly in-sync with the associated core database. If a new core database is handed over, the non-core databases will often need to be updated - but we only run the non-core datachecks when a new non-core database is handed over. If nothing is handed over, we have no mechanism to warn us of inconsistencies. So we need something that triggers those datachecks.
This PR introduces a new pipeline that runs the subset of non-core datachecks that relate to synchronisation with the core db. It is intended to be run by Production when the core handover is complete. The ensuing datacheck reports will undoubtedly have failures, because new core databases will have introduced …
=> Non-core synchronisation datacheck pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/StableID/EmailReport.pm
We are not supposed to have duplicate stable IDs either within or across species. We can make sure of the former with the GeneStableID datacheck, but the latter is not enforcable, because we are not in control of the stable IDs that are used in the gene sets that we import, rather than annotate in-house.
We want to have a report of duplicate stable IDs, so that we can a) check for egregious errors, and b) understand the scale and nature of duplication, and even if it can't easily be tackled we can provide this information to those using the Ensembl data, so that they can account for it if necessary.
There was a nascent datacheck for this, but it was only comprehensive if you provided the right parameters; it was easy to get a passing result by accidentally omitting a database server. It …
=> Add duplicate report to Stable ID pipeline

scripts/copy_ftp_release.pl
A user reported that a protist VCF file was truncated. On further inspection, all GVF and VCF files for fungi, metazoa and protist species had the same problem. The cause was a bug in the file we use to copy files, when there have been no new/updated variation databases in a release.
The code tried to update a release version directly in the compressed file, and that bit works, but I think the implementation of this functionality in Perl is a bit flaky. At some point during processing the file handling fails without raising an error, so you have a partial file and no indication that anything has gone wrong.
To resolve this, I removed the bit of code which was parsing the gzip file line by line in Perl, and did a gunzip-sed-gzip command instead. Both take about the same amount of time, but …
=> Fix copy script to produce non-truncated GVF and VCF files

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Run RefSeq dependent ZFIN parsing last to avoid any race conditions.
We have several ZFIN related files to parse. …
=> ENSCORESW-3554: run RefSeq dependent ZFIN parsing last

modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Having "\r" characters in fields is problematic for mysql dumps; without having server access to do the dumping, escaping the characters is surprisingly difficult. However, stripping out "\r" with a sed command causes significant problems, because for fields with compressed/binary data, this often corrupts the data.
The lesser evil is to have "\r" characters in our dump files - this impacts fewer tables, and is immediately obvious, because loading the data fails. The corrupted binary fields weren't spotted for several releases, and was time-consuming to fix.
But, hopefully that shouldn't be an issue in future, because this PR is in conjunction with a new datacheck, that disallows "\r" in any database field ("\t" and "\n" are OK in the mysql dumps, although since they are potentially …
=> Don't remove "\r" characters from mysql dumps

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpVEP_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpVariation_conf.pm
Wrappers for the pipelines provided by the Variation team, that incorporate Production-specific processing steps. This is in anticipation of future changes to the ftp layout and file naming conventions, to provide flexibility in how we process the files. It also eases the current process somewhat, automating the post-pipeline tidying/rsyncing that is currently done manually.
=> Wrappers for the VEP and GVF/VCF pipelines

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Production/EmailSummaryCore.pm
The core stats pipeline was using the geneset and assembly information in the metadata db to decide when it needed to be run. This does not take into account some scenarios which affect the statistics: for example, if the members of a biotype group change, or if 'karyotype_rank' attribs are added. The easiest way to tackle this is to run the appropriate group of datachecks, and run the pipeline for any species which fails. This is a bit redundant, because we don't necessarily need to re-do density calculations if only a biotype has changed (for example), but the pipeline is not _that_ expensive to run, so we tolerate this for the sake of a simpler pipeline to maintain.
We ended up with species with out-of-date statistics because we didn't have sufficient triggers in place to re-calculate …
=> Base decision-making in Core Stats pipeline on datachecks

modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
This is resolved for future releases, by fixing the source tables in the production database.
=> For release 102 only, we need to replace \r characters in three tables.

scripts/assembly_converter/populate_assembly_converter_dir.sh
Add the option to run `populate_assembly_converter_dir.sh` script for either _vertebrates_ or _non-vertebrates_
As assembly files are generated separately for _vertebrates_ and _non-vertebrates_, this option will make possible to run `populate_assembly_converter_dir.sh` on only _vertebrates_ or _non-vertebrates_ in case files generation isn't completed for one of the two.
Gives more flexibility (and possibly speeds up) the overall release process as _assembly converter_ step doesn't have to wait for all the tools files to be generated.
Either _vertebrates_ (`-V`) or _non-vertebrates_ (`-N`) options must be provided when running the script.
=> Run populate_assembly_converter_dir.sh for verts/nonverts independently 103

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Run HGNC parsing later in the pipeline
HGNC parsing uses already loaded RefSeq xrefs to create mappings on the fly. …
=> ENSCORESW-3565: run HGNC parsing after RefSeq parsing

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
Required when running for bacteria.
=> Bump up memory allocation for core stats pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Pipeline config for vertbrate GFF3 tidying/validation was hard-coded to an out-dated version of 'gt' - and was consequently producing GFF3 with invalid phases. Remove this to use the latest version installed in the Ensembl software environment. (Also removed some old commented-out code, and the 'prev_rel_dir' parameter which was the same as in the parent config.)
Valid GFF3!
Pipeline won't work if you have not configured the Ensembl software environment - but we have that as our standard practice.
Not explicitly tested, but the non-vert config has been using the default 'gt' for many releases, and that works fine.
=> Fix GFF3 tidying/validation in ftp dumping pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SampleData_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/SampleData/GenerateSampleData.pm
The analysis that derives a 'good' example gene/transcript/location was taking hours and large (sometimes >16GB) amounts of memory. This is excessive - it's not important to get the absolute best example gene, we just need something that is in a decent-looking gene tree, and is preferably in RefSeq/UniProt. Rather than spend time optimising, we can just reduce the number of trees we look at in the first place - currently ~6000 trees are examined. Reducing that by an order of magnitude, by limiting the set of results to 500, cuts down both time and memory usage.
Pipeline runs faster, uses less memory.
We do not guarantee that we choose the best possible gene, optimised for all our criteria.
Run for a test species - new code took 37 mins and 2GB, rather than 2 hr 29 mins and 9GB. Different …
=> Reduce Sample Data time/memory usage

modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
Add explicit disconnects, so that long-running queries don't cause 'mysql has gone away' errors.
This is a problem for release/102 dumping, so PR is against that branch - will replicate on release/103.
Dumps complete without timing out.
None.
Modified code run for sample long-running jobs - completed successfully.
=> Add explicit disconnects in variant json dumps

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TSLsAppris_conf.pm
Simplify config file for TSL/Appris pipeline - there were mandatory parameters and resource classes that were never used, as well as unhelpful comments.
Simpler config and init_pipeline commands
Pipeline successfully initialised and run with these changes.
=> Removing redundant comments, parameters, and resource classes from TSL/Appris pipeline

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Assembly_Chain.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base_Filetype.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/DirectoryPaths.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_FASTA.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Genome_FASTA.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Metadata_JSON.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.txt, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Exists.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Symlink.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Symlink_RNASeq.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Verify.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Xref_TSV.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpCore_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Some modifications for the Rapid Release ftp pipeline:
- restrict xref timestamp to xref-related tables
- refactor directory creation code - it was based on data being either 'genome' or 'geneset' related, but we have 'rnaseq' now, and will have others in future, so create the concept of a 'data_category' to capture this in an extensible way.
- set line width for geneset FASTA files to 60.
- presence of rnaseq files is checked, and symlinked directory structure created for web
- new json file for reporting species, based on the 'is_current' release in the metadata db
=> RR ftp pipeline updates

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
The URL for DBASS source download has changed, this is updated in the appropriate config file.
The file download …
=> ENSCORESW-3608: DBASS URL change

modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
Json dumps not settings release param causes the script to us the "is_current", which can have unattended side effects. 
FTP dumps json part. 
Can use whatever release number instead of `is_current` one. 
None
Dependencies
------------
=> Added release parameter to ensembl_genomes_release.

modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm
Fix typo that upon pipeline creation (`init_pipeline.pl`) would lead to the following error:
```
The runnable module 'Bio::EnsEMBL::Production::Pipeline::LoadFamily::AddFamilyMembers' cannot be loaded or compiled:
syntax error at [...]/ensembl-production/modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm line 112, near ");"
Global symbol "$gene_member" requires explicit package name at [...]/ensembl-production/modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm line 117.
```
=> Fix typo in AddFamilyMembers.pm

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Metadata_JSON.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.txt, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Exists.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Xref_TSV.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
A collection of modest updates:
- metadata report now uses taxonomy db for species names, as connecting to core db was problematic
- xref dumping is more memory-efficient
- checksum and readme files for rnaseq are consistent (no ".1" suffix)
- README file is stored in a single location on the public ftp, and symlinks are created in all geneset and genome sub-directories
Modified pipeline/modules run successfully.
=> Further updates to RR ftp pipeline

modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
The module for dumping GFF3 was failing in standalone mode, because it was expecting a hive database; check if such exists before trying to run a method against it.
=> GFF3 dump - standalone fix

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Exists.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Missing.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
The file dumping pipeline for Rapid Release uses the database to define expected rnaseq files, in order to create symlinks used by web and to sync to the public site; if they did't exist, the pipeline was failing. This doesn't really fit the RR paradigm - we won't necessarily be able to fix it immediately, and imperfect data is OK. So the pipeline now warns about missing files, but then proceeds with whatever is there, and completes normally.
By default, for each species that lacks rnaseq an email is sent, listing the missing files. It is send by default to the 'email' parameter value, which will be whoever initialised the pipeline, if not explicitly set. But the email about the rnaseq files can be sent to a specific individual or team, by using the 'rnaseq_email' parameter.
More robust …
=> RR file dump pipeline sends emails about missing RNA-seq

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Fix ##sequence-region metadata when tidying GFF3 (AFAIK, this only matters for human chrY, in which a gene is annotated partly in a PAR).
GFF3 dumps for human chrY are valid.
Tidying is potentially slower - but wasn't noticeably so when tested.
=> Fix ##sequence-region metadata when tidying GFF3

modules/Bio/EnsEMBL/Production/Pipeline/StableID/sql/index.sql
KEY MYSQL KEY word doesn't work with sta-5 MySQL version
Fix by using UNIQUE index instead
Build indexes after ensembl_stable_ids is built.
No more error while building indexes.
None
Dependencies
------------
=> fix Stable Ids Index creation sql command

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/RNAGeneXref_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/RNAGeneXref/AnalysisConfiguration.pm, modules/Bio/EnsEMBL/Production/Pipeline/RNAGeneXref/LoadRNACentral.pm, modules/Bio/EnsEMBL/Production/Pipeline/RNAGeneXref/RNACentralXref.pm
A new, small pipeline to add RNAcentral checksum-based xrefs to the RNA genes in a core db. This is the analog of UniParc xref functionality which is now in the ProteinFeatures pipeline (#541).
It is intended for Rapid Release only (although it could be used for non-vert divisions, because I don't think RNAcentral xrefs are part of their SOP), because GOA provide their annotations against RNAcentral accessions, so we need those to join things up and maximise our GO terms. It is quick to run: loading the checksums takes ~8 mins, and the annotation itself ~5 mins per species.
Annotate RNA genes with a "hub" xref, which can be used to link through to all the individual RNA resources. 
Maximise our ability to use GO annotations provided by the GOA team.
It's still another pipeline that we …
=> New pipeline for RNA gene xref annotation

scripts/ftp/upload_ena_xrefs.sh
Use [lftp](https://lftp.yar.ru/) instead of `ftp` in `upload_ena_xrefs.sh`
If the connection is lost (e.g. slow server timing out), LFTP will automatically re-connect and restart the upload from where it was left.
Usage is also cleaner.
=> Use lftp instead of ftp for ENA xref upload

modules/Bio/EnsEMBL/Production/Pipeline/MirrorLoad/DeleteDBs.pm, modules/Bio/EnsEMBL/Production/Pipeline/MirrorLoad/ListDatabase.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MirrorLoad_conf.pm
In release cycle after non-core handover and processing all the mart we copy the databases from staging  servers to mirror. 
This pipeline help to delete the old release(n-3) from mirrors and copy the new release dbs from staging to mirrors 
Major Steps in Pipeline:
ListDatabasesToDelete
Used MetaDataDBAdaptor to list all the databases for ante-penultimate DBs (release - 3)
DeleteDBs
Delete ante-penultimate DBs (release - 3)   from mirror
ListDatabaseToCopy
Used MetaDataDBAdaptor to list all the databases for given release
CopyToMirror
Copy given db from staging server to mirror based on division
-Test case:
copy vertebrate marts to mirror-mart-1
init_pipeline.pl MirrorLoad_conf.pm $($HIVE_SRV details hive) -registry $registry  -division vertebrates  -process_mart 1 -hive_force_init 1 …
=> Pipeline mirror load

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base_Filetype.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Make parent directory group-writable, so that genebuild team can create an 'rnaseq' directory for an existing species.
Genebuild team were not able to create a directory for Rapid Release rnaseq data if the species already existed.
Module run in isolation.
=> Rapid Release ftp directory permissions

modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
The GOA team provide terms annotated against UniProt and RNAcentral identifiers (plus some other misc. sources) - however, a bug was introduced 4 years ago that prevented the loading of RNAcentral-derived terms, with the exception of those linked to microRNAs (which represent a very small amount of the total RNAcentral annotation). 
This fix continues to treat microRNAs differently, loading the precursors rather than the product (because we have the former not the latter in our dbs), but uses the given accession in all other cases.
Test pipeline was run for panda - gained ~5000 GO terms linked to RNA genes.
=> Load RNAcentral-derived GO terms in GPAD pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/RNAGeneXref_conf.pm
Restructure pipeline a bit, so that we don't bother doing a backup of the tables if we are not going to process a species.
We had a cryptic failure when annotating RNAcentral xrefs, where the data got linked to two different analyses; sometimes that can happen if a job is restarted, but it couldn't be replicated to test further. Perhaps just a transient error, but the pipeline was actually doing a bunch of work it didn't need to do (backup dumps and datachecks when no data had changed), so it couldn't hurt to eliminate that, and reduce the concurrency and load on the db.
New pipeline initialised and run to successful completion.
=> RNAcentral xref pipeline restructure

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base_Filetype.pm
Bug fix, only try to make parent directory group-writable if we have just created it, otherwise we could be trying to make a directory we don't own writable, causing an error.
File dumping pipeline successfully run.
=> RR ftp permission - bug fix

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.txt, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Xref_TSV.pm
The Xref dumping is very slow using the API; this rewrites the module to use a handful of SQL queries, which are vastly quicker (~5 mins, rather than hours), and probably easier to understand than the previous set of API calls. Memory usage is reduced too. 
These changes also fix a bug where sources for GO terms were not correctly retrieved - the API-based code was not filtering on the transcript, so the sources were reported for all transcripts. Further, only one 'linkage_type' was reported in these cases; this is a per source property, however, so the value was moved to the compound 'sources' field. And the name of the field changed too, because 'dependent_sources' could be taken to mean that these were annotations dependent on the GO term, rather than the other way around.
File dumping …
=> Rewrite Rapid Release Xref TSV file dump to use SQL not API 

scripts/apply_patches.pl
Prevent matching database names that include dbname parameter value as
substring.
For example calling the script with `-dbname ensembl` will
*not* match `ensembl_production`
=> Fix apply_patches dbname parameter matching as substring

modules/t/11-searchdumps_dumpgenes.t, modules/t/test-genome-DBs/hp_dump/core/biotype.txt
The biotype table was lacking values for the so_term, which had been introduced into the test, so the test was failing. Also corrected a typo, where a full stop instead of a comma was causing the expected hash structure to get mangled.
Test suite passes!
=> Updating test biotype table and related test

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/AnalysisConfiguration.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScan.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScanVersionCheck.pm
On Codon we have a centrally-managed version of InterProScan, which is much easier for us to manage, but needs a little bit of adaptation in the pipeline. (https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-6789)
For a given instance of the pipeline, we want to run the same version of interproscan; but the interproscan team might update the 'current' symlink mid-pipeline. So, resolve the 'current' link to a distinct version at the start of the pipeline, and pass that version to subsequent modules that need the path to the executable.
A corollary of the above point is that the specific version does not need to be hard-coded in the config file.
Versions of the Interpro source dbs are also no longer hard-coded in the conf, but are instead determined by running interproscan.sh with no …
=> Modify Protein Features pipeline for Codon cluster

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/AnalysisConfiguration.pm
We need a bit more flexibility in 'seg' execution, so that we can always force it to run, even if there are already features annotated. The use case is for human and mouse, where we might have partial annotation, and we want to re-annotate everything.
The assumption of the pipeline now reflects usage, and treats 'seg' the same as the InterPro sources, in that it is always run of features do not exist. By default, it is not run if features exist, but this can be overriden by setting the 'run_seg' paramter to 1.
Can deal with all use cases for _seg_ annotation.
Logic of pipeline has slightly changed interpretation of the parameter, which isn't ideal; but this parameter would rarely, if ever, be used when running pipelines, so this shouldn't affect anyone.
Pipeline run for human and mouse.
=> Modify Protein Features pipeline, 'seg' execution.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/UpdateComparaMemberNamesDescriptions_conf.pm
I was a bit hasty in deleting this pipeline during the Codon migration updates;it is no longer required for normal divisional compara dbs, but we still need it to update pan-compara...
=> Reinstate Compara gene name update pipeline.

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base_Filetype.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3_ENA.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpENA_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
This differs from our normal export in a few ways; the versioned stable IDs for all features are set as 'Name' attributes (only gene is required to have a name, but it doesn't hurt to be consistent).
The versioned INSDC accessions are used to identify sequences; if a region is a chromosome, the name is given by the 'chromosome' attribute. Circular regions have the 'Is_circular' attribute; and if a region needs anything other than the standard Codon table, there is a 'transl_table' attribute.
Some aspects of the file are in line with the NCBI spec: gene_id, transcript_id, protein_id attributes all contain the versioned stable ID; exon order is given by the 'exon_number' attribute rather than 'rank'. The biotype of a gene is given by a 'gene_biotype' attribute, rather than 'biotype'.
Two …
=> GFF3 export, formatted for ENA submission.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Some jobs were hitting the memlimit during the step where the file is renamed after being sorted. For reasons I couldn't make out, this was not being properly detected and spawning a subsequent 'high_mem' job. But might as well increase the default memory to avoid teh problem in the first place.
=> Increase memory for GFF3 ENA format dumps.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Several `StoreProteinFeatures` jobs regularly fail with MEMLIMIT.
Species involved: mouse, drosophila, suricata
`StoreProteinFeatures` jobs that would fail with MEMLIMIT will be automatically passed to `StoreProteinFeatures_HighMem` and ran.
Nothing comes to mind
=> Add StoreProteinFeatures_HighMem to PF pipeline

modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm, modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/ReportFailures.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FtpChecker_conf.pm
Missed this config when doing earlier updates for Codon execution - Pipeline now inherits from the standard Base
config, to enable execution on the Codon cluster.
Also, a couple of improvements to the pipeline:
1. Drop TSV checking - we don't have clear expectations of these files, so we end up with lots of spurious 'failures', amongst which it's easy to miss important failures.
2. Rather than rely on the person running the pipeline to find the results file and look at it, send an email (if there are failures) with the file location, and attach file if it's not too big.
Confluence updated: https://www.ebi.ac.uk/seqdb/confluence/display/GTI/FTP+Checker+Pipeline
Pipeline runs on Codon; genuine failures are easier to spot.
Test pipeline run on Codon, new functionality verified.
=> Update FTP Checker pipeline for Codon execution.

modules/Bio/EnsEMBL/Production/Pipeline/Common/MultiDbFactory.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpMySQL_conf.pm
This is a refinement of #575.
We _can_ retrieve 'compara' dbs via the DbFactory, but it's harder to get 'ancestral' dbs. Both of these are multispecies dbs, so it makes sense to process them alongside all the other dbs. (The 'ancestral' dumps were working, but sort of by accident, being included with the mart processing.)
Also, it's easier, and more consistent with other dumps, if we don't require division parameters for mart dumps, and assume that we want them for all divisions, if not specified.
Test pipeline successfully run for plants (which has 'compara' and 'ancestral' dbs).
=> For MySQL file dumps, treat compara as 'multi' database.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm
while moving to codon, we cleaned up our resources class names and made a more generic use of them in our pipeline. So we removed the resource name "1Gb_job! from our configurations files (because this is anyway the default resources allocation
While initialising Bio::EnsEMBL::Production::Pipeline::PipeConfig::GeneNameDescProjection_protists_conf I noticed the error. 
GeneNameDEscriptionProjection pipeline. 
Avoid compara updates dependency located in there : https://github.com/Ensembl/ensembl-compara/pull/327
None
Dependencies
------------
=> Reinstantiate rc_name="1Gb_job" for compat with Compara resources

scripts/copy_ftp_release.pl
- Remove FASTA (fa.gz ext) regex from `gzip_files` as FASTA file names
don't include the release number anymore.
- Change GTF (gtf.gz ext) regex matching characters after the release
number un-greedily, removing ambiguity (if the names are correct).
Files copied using `copy_ftp_release.pl` should not have parts of the assembly mismatched with the Ensembl version numbers in the target file name. 
Might not cover all possible cases.
=> Fix regexes for gzip file names in copy_ftp_release.pl script

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_plants_conf.pm
GeneName Description Project Pipeline for plants fails as compara db includes  vertebrate species as outgroups. 
We do not have vertebrate species (i.e Human) on the target staging.  
compara team have provided with new param to filter the given species list , for more details on exclude_species param
https://github.com/Ensembl/ensembl-compara/pull/322
Related JIRA tickets:
ENSCOMPARASW-4673
ENSPROD-6669
=> Exclude outgroup species

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
The renaming needs to be restricted to a subset of dbs; otherwise running the pipeline for bacteria leads to retrieval of db names for all divisions from the metadata db, which then fails for the non-bacterial dbs. Rather than ignoring those, which could lead to us overlooking true discrepancies in the expected dbs, filter based on division. Our SOP is that we will always be passing this parameter in any case, to get the relevant marts and comparas.
Also, renamed the parameter from 'division' to 'multi_division', to avoid confusion with the SpeciesFactory 'division' parameter, since the usage/behaviour is different here.
Avoid spurious rename failures, which should not be attempted in the first place.
Less confusing parameter name.
None I can think of.
Test pipeline initialised.
=> Pass division parameter to rename factory

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabaseDBA_conf.pm, src/python/ensembl/production/hive/ProductionDBCopy.py
Remove 3 hours timeout from ProductionDBCopy module
Hive analysis that uses that module won't fail if the copy job takes more than 3 hours to terminate
=> Remove timeout from ProductionDBCopy module (main)

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/MySQL_TXT.pm
Standalone execution was complaining without use Bio::EnsEMBL::DBSQL::DBAdaptor;
Command used:
standaloneJob.pl Bio::EnsEMBL::Production::Pipeline::FileDump::MySQL_TXT   -db_url ${SRV_URL}${DBNAME}   -dbname ${DBNAME}   -output_dir ${OUTPUT_DIR} -dump_dir ${OUTPUT_DIR}
Error:
Standalone worker 618133 : specializing to Standalone_Dummy_Analysis(unstored)
Standalone worker 618133 : WORKER_ERROR : Can't locate object method "new" via package "Bio::EnsEMBL::DBSQL::DBAdaptor" (perhaps you forgot to load "Bio::EnsEMBL::DBSQL::DBAdaptor"?) at /hps/software/users/wormbase/parasite/reposi
tories/ensembl/branch-105/ensembl-production/modules/Bio/EnsEMBL/Production/Pipeline/FileDump/MySQL_TXT.pm line 84.
Standalone execution will run without problems Bio::EnsEMBL::DBSQL::DBAdaptor;
standaloneJob.pl …
=> Add use module to MySQL_TXT.pm

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Before removing Interpro xref records, remove object_xref records
related to such xrefs; as some object_xrefs might have been previously
loaded alongside those xrefs and would end up "orphaned"
Removes those object_xrefs related to xrefs that will be removed because related to Interpro records that will be replaced.
Dependencies
------------
=> Remove object_xref related to Interpro in ProteinFeatures

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
Pipeline(ensembl stable id generator  )fails at analysis step create_index for  any unexpected reasons and it retries to run the job as default retry set to 3 which leads to fail with subsequent error Duplicate key name 'stable_id_db_type ' as index already created with this name.
Due to this retry behavior we are unable to catch original error so by setting retry value to zero we can debug the route case
=> set max retry to 0 for create index analysis

.travis.yml
Try to fix for good potential issues with master/main branches odd configuration across  ensembl fetched repo. 
Don't bother with `master` or `main` being present as sources branches when building, by using `ensembl-git-tools` git commands with fall back branch. 
No need to specify default branch per repo and failed build when remote project doesn't have a master any more. 
None
Dependencies
------------
=> Fix default branch retrieval with usage of `ensembl-git-tools`

modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm, modules/t/11-searchdumps_dumpgenes.t
Transcript Attributes added to unified dumps .
New attribute "attrib" added to each trancript 
example:
"attrib": { 'TSL': 'tslNA', 'appris': 'principal1', 'name': 'AC008175.3-001', 'xref_id': 'OTTHUMT00000102233', 'MANE_Select': 'NM_004676.2', 'is_canonical': 1, ........... }
=> Added transcript attributes in unified dumps

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_plants_conf.pm
Add default parameter added by compara to our production configuration
https://github.com/Ensembl/ensembl-compara/commit/d4e1fb4e15b312db95d1d7c43035d89e3025894c
Fixed typo in following updated from initial default values for plants (missing $ in self!)
Gene Name Projection Ran by production
Production can run our release pipelines.
None, but we need a SOP about Compara pipeline updates. 
Dependencies
------------
=> Added defaut parameter to Compara GeneNameDescProjection_conf.pm

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/RefSeqDatabaseParser.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/UniProtDatabaseParser.pm
Fixing package names for new xref parsers.
The UniProt and RefSeq parsers used for the new pre-parsing step of the …
=> Fix package name for renamed parsers

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpSpeciesForGOA_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
Remove `dm` queue for loading (file are supposed to be synced to /nfs before proceeding. See SOP)
Dm queues are to be used for GOA dumps files until we add the required steps in pipeline
Path to dump doesn't exists when ran from a standard production node. 
For GOA load part, since we are supposed to move files onto our nfs before run, (because of the limitation to 10 jobs per user on dm), no need to force the load from dm.
Files are dumped in the right place. 
Nonw
Dependencies
------------
=> Use `dm` queue for goa dumps.

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_plants_conf.pm
Fix `GeneNameDescProjection_plants_conf`, set `exclude_species` in `default_options` instead of `pipeline_wide_parameters`.
Additional species can be excluded when istanciating the pipeline by specifying `-antispecies` param for `init_pipeline.pm`.
Note that `exclude_species` is used by `Bio::EnsEMBL::Compara::RunnableDB::GenomeDBFactory` only.
=> EP-7663: Fix GeneNameDescProjection_plants_conf

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Following advises from sysinf
Message from sysinf: 
db_copy_egphx_b_106-Hive-default-2_1
The memory requested is 1 GB and max used is 400 MBytes.
Better codon nodes resources management.
Reduce amount of tasks to default queue
None
Dependencies
------------
=> No need to use a 1gb worker to follow DBcopy jobs

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefDownload_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProcess_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/EmailNotification.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ParseSource.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleDownload.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/SchedulePreParse.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleSource.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_all_sources.json, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Making the xref runnables backwards compatible, to allow users to run the old Xref_update_conf pipeline without …
=> Fix backwards compatibility issues and general bugs

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/SchedulePreParse.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleSource.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_all_sources.json, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Final backwards compatibility changes added to the xref pipeline.
These changes allow users to run the old xref pipeline without any concerns, and it allows the run of the new pipeline without the use of pre-parsing. This PR also contains a fix to the ZFIN_desc download URL, reverting it back to ftp as the https one doesn't work).
This PR is related to [#612](https://github.com/Ensembl/ensembl/pull/612) opened in the ensembl repo.
Xref pipeline backwards compatibility.
None
Dependencies
------------
N/A
=> New xref pipeline backwards compatibility

modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
module File::Find::Rule->file()->name("*_genome.xml") unable to find the genome xml files present in species sub directories recursively.
Fix: method File::Find::Rule->directory  finds all the species directories in the search dump folder and this list of  species directory is given as input to method File::Find::Rule->file() to find all the genome xml file present in search dumps for given division.
=> fix for empty Genome xml file in search dumps

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
Adding the canonical and MANE flags for transcripts and their underlying features in the GFF3 files.
JIRA Ticket …
=> Add transcript tags to GFF3 files

scripts/py/regulation_ftp_symlinks.py
New species have been added to the scrip to create the symlinks under the misc directory in the FTP.
Parameters to …
=> update regulation_ftp_symlinks script to add more species

modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/HiveLoadAlphaFoldDBProteinFeatures.pm, modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/MakeAlphaFoldDBProteinFeatures.pm, scripts/py/alphafoldUpdate.py
Changes for fixing:
- duplicated `protein_feature` records in core DBs
- missing new `protein_feature` records for non-GIFTS species
- ".A" hit names for `protein_feature` 
Create AlphaFold protein features for additional species, which are not necessarily represented in GIFTS DB.
Fixing bugs and mitigating current pipeline design issues.
For non-GIFTS species, the Uniprot entry is retrieved from Xref data. These Xref are required to be of `info_type` DEPENDENT, but that is not necessarily the case for some non-vertebrates species.
In these latter cases, the AlphaFold data cannot be mapped, `protein_feature` are not created, and data checks will fail.
These drawbacks will be addressed in `release/109`.
The changes were manually successfully tested. No automatic testing procedure was …
=> Fixes for non-GIFTS species

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Datacheck output creating duplicate jobs in the speciesfactory with resulted running jobs multiple times and failing to meet desired inputs.
details are in ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7770
=> fix for recurring error

cpanfile, modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/CreateAlphaFoldMapping.pm, modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/HiveLoadAlphaFoldDBProteinFeatures.pm, modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/MakeAlphaFoldDBProteinFeatures.pm, modules/Bio/EnsEMBL/Production/Pipeline/Common/MetadataCSVersion.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/AlphaDBImport_conf.pm
The AlphaFold pipeline currently uses mapping files to associate proteins in a species with the prediction data. This commit changes the pipeline to create these mapping files in a first step.
The pipeline uses scratch_large_dir, which is created at the beginning and deleted when the pipelines has finished.
Includes a dependency on Gzip::Faster. It is 8 - 10x faster than the default IO::Compress::Gzip.
No more preparing the map files.
Pipeline is easier to run, less room for errors.
Pipeline tested manually. Code has no impact on other pipelines.
Dependencies
------------
New dependency on Gzip::Faster
=> AlphaFold pipeline: integrate map file creation

modules/Bio/EnsEMBL/Production/Pipeline/GeneTreeHighlight/HighlightGO.pm, modules/Bio/EnsEMBL/Production/Pipeline/GeneTreeHighlight/HighlightInterPro.pm
As a result of recent changes to the Ensembl Compara schema ([Compara PR #499](https://github.com/Ensembl/ensembl-compara/pull/499)), a `Compara::DBSQL::XrefAssociationAdaptor` method called in the gene-tree highlighting pipeline was executing very slowly due to an SQL query of a gene member by `stable_id`. The relevant SQL can be updated to address this issue, but the fix in `ensembl-compara` can be made simpler by updating `ensembl-production` to create `XrefAssociationAdaptor` using a `Compara::GenomeDBAdaptor->db()` object instead of `Compara::GenomeDBAdaptor->db()->dbc()`. This PR would implement that change in the `HighlightGO` and `HighlightInterPro` modules.
In the `HighlightGO` and `HighlightInterPro` modules, the `XrefAssociationAdaptor` is initialised with the relevant …
=> Init XrefAssociationAdaptor with GenomeDB adaptor DB

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/DirectoryPaths.pm
- added in outputs
Wrong configuration manipulation for Variation/geneset directory path (able to add the YYYY_MM to the path)
Added as well for homology data category. 
FTP directory structure to include the Assembly date in the path for variation/homology/geneset paths in FTP. 
RR FTP dumps new path layout
Include the right one for all use cases. 
None. 
Dependencies
------------
=> Fix issues with variation|geneset|homology subdirectories setup

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Base.pm
Fixing bug with using the RefSeq catalog before replacing the release number.
The RefSeq catalog URL contains a …
=> Bugfix: replace release nuber in catalog before fetching

scripts/ftp/checksums.pl
`ensgen` user has been deprecated, so we don't need anymore this requirement, though now the default ftp user is `ensemblftp`, so changed that. The lit of autorised user is extended to our usual virtual users. 
Checksums.pl manual run
No need any more to add the `-ignore_user` when running with ensemblftp.
None
Dependencies
------------
=> Checksum.pl updates to remove `ensgen` user test

scripts/assembly_converter/populate_assembly_converter_dir.sh
Fixes wrong FTP target path for vertebrates ({division} sub directory doesn't exist for vertebrates)
Assembly converter files generation for release.
No more file not found
None 
Dependencies
------------
=> Fixed find path for `vertebrates` division on FTP live dir.

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/CleanupUniprot.pm
Fixing a bug that was discovered in the Uniprot cleanup code
When the cleanup code was first added, all comments …
=> Keep specific caution comment in uniprot file

modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/CreateFamilies.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/LoadFamily_conf.pm
This PR integrates the Compara `GeneMemberHomologyStats` pipeline part into the Production `LoadFamily` pipeline.
Currently two pipelines - `LoadFamily` and `EG::GeneMemberHomologyStats` - need to be run on each division for which InterPro Families are being generated. The integration of the latter pipeline into the former has the potential to streamline this process.
Instead of running two separate `LoadFamily` and `EG::GeneMemberHomologyStats` pipelines, it would be possible to run just one `LoadFamily` pipeline including the functionality of the integrated `GeneMemberHomologyStats` pipeline part.
No drawbacks anticipated.
No unit tests have been added or modified. However, a test pipeline has been initialised to confirm that the `GeneMemberHomologyStats` pipeline has been integrated …
=> Integrate GeneMemberHomologyStats into LoadFamily

scripts/py/regulation_ftp_symlinks.py
Refactor regulation FTP symlink script.
With this change, this script will be in charge of creating Regulation FTP symlinks from data files folders to:
- GENE-SWITCH project folder under the public miscellaneous directory [PEAKS, SIGNALS] - misc/gene-switch/regulation
- Release specific folder [PEAKS] - release-[RELEASE_VERSION]/regulation/[SPECIES]/[ASSEMBLY]
Dependencies
------------
python3
=> Refactor regulation FTP symlink script

modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/HiveLoadAlphaFoldDBProteinFeatures.pm
Alphafold analysis name change to fit Biomart table names
Table Name generated for Biomart are too long with this analysis name
Related:
https://github.com/Ensembl/ensembl-datacheck/pull/548
https://github.com/Ensembl/ensembl_nf/pull/1
_If applicable, describe any possible undesirable consequence of the changes._
Dependencies
------------
=> Changed `alphafold_import` to `alphafold` to fix Biomart Tables length

modules/Bio/EnsEMBL/Production/Pipeline/Common/Gzip.pm, modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpMySQL_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFile.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileMetadata.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm, modules/Bio/EnsEMBL/Production/Pipeline/TSV/Gzip.pm
Swapped direct calling of gzip with using the perl module.
Separated compression from SQL queries.
Will be used in all mySQL dumps and all core dumps.
Escapes the compression bug and allows us to restart failed compressions without restarting the queries.
The module gzip may be slower.
Pipeline was tested with mysql dumps and core non_vert dumps. 
Tested using a single species. 
Dependencies
------------
No new dependencies.
=> Added a failure if gzip fails to complete properly

modules/Bio/EnsEMBL/Production/Pipeline/Ga4ghChecksum/ChecksumGenerator.pm
The current pipeline is capable of inserting a checksum representing an empty sequence. This avoids inserting them.
Empty sequences can happen with CDS which you only get with transcripts with a translation. Instead we just sniff the seq content and skip the logic when it is empty.
MD5 checksums like `d41d8cd98f00b204e9800998ecf8427e` and sha512t24u `z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXc` indicate empty strings.
We do less work and fewer inserts
None really. 
Minimal testing because this is difficult on my setup
Dependencies
------------
None
=> Avoid inserting checksums of empty sequences

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/LoadRefget_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Refget/RefgetLoader.pm, scripts/refget/check_sequence_refget.pl
New pipeline which
- Takes in a core database
- Generates the checksums
- Checks if there has been drift against previously stored checksums (can be turned off)
- Checks if toplevel seqs are in ENA refget (avoids storing if they are)
- Inserts into Perl Refget using its DBIX::Class
- Creates transactions around each slice
- Will only insert new molecule data for the same id,sequence,type when it's a new release
We need sequences in refget for MVP and this loads them from a core database rather than a FASTA file.
We don't need to go through the FTP site and we get better coverage of the transcripts (already an issue)
Might be slow.
I've run this locally and tested. Point me at the test suite and I'll do that too if needed.
Dependencies
------------
Deployments must have a copy of the Perl …
=> Generate checksums and insert into Perl refget

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpCore_conf.pm
Remove RNASeq_exists DC test from dump, now obsolete. 
Stop spamming GB team with obsolete message for RR FTP dumps. 
No mails
Actual missing files will be really missing.
Dependencies
------------
=> Removed RNASeq tests from FileDump for RR

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/CleanupRefseqPeptide.pm
Fix for the RefSeq peptide files cleanup.
A bug was discovered in the process the cleans up the RefSeq peptide …
=> RefSeq peptide Cleanup Fix

modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
In the code, scalar was called on a hash reference. This is either not permitted or produces a warning, depending on the Perl version. Fixed.
=> Fix for "scalar on reference"

modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/AlphaDBImport_conf.pm
- The pipeline config did not pass the gifts_pass parameter to the runnable
- Added an early check for gifts_pass so it is required at pipeline creation
- cleanup was running too early. Changed the logic
=> Alphafold - Fixes for pipe config and cleanup

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleSource.pm
Adding line missed in last PR.
When changing the use of "ls" into perl's "readdir" in the PR #865 , this check was …
=> Add check for unvalid readdir output

modules/Bio/EnsEMBL/Production/Pipeline/Production/PepStats.pm
Fix a bug where the runnable continues running and finishes silently even if the binary for pepstats is not available.
Add a simple check for when the pepstats binary is not available.
Used in Core stats pipeline. Currently if pepstats is missing, PepStats still completes silently, then PepStats_Datachecks finds that no peptide attributes have been added to the database.
Prevent the runnable from silently finishing when it should fail and be restarted with a working binary path.
None
No tests added. Used this commit to run a core stats pipeline when pepstats was missing in the environment. After adding a working path to a pepstats binary and restarting the PepStats jobs, the next datachecks pass.
Dependencies
------------
None
=> Check that pepstats is there

modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/CleanupUniprot.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/UniProtDatabaseParser.pm
Fixing some bugs discovered during the 112 run.
During the 112 run of xrefs, a bug in the UniProt file parser was …
=> Fix uniprot gene name + cleanup bugs

modules/Bio/EnsEMBL/Production/Pipeline/TaxonomyUpdate/QueryMetadata.pm
- Filling out the template is required.
This PR modifies the `TaxonomyUpdate::QueryMetadata` Hive runnable used in the `TaxonomyInfoCore` pipeline to throw …
=> Flag outdated taxon_ids in TaxonomyInfoCore pipeline

modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm, modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/CreateFamilies.pm
With the changes in this PR:
1. InterPro Family data are loaded only for canonical members.
2. Existing MLSS and …
=> Load InterPro Family data only for canonicals

modules/Bio/EnsEMBL/Production/Pipeline/StableID/sql/index.sql, modules/Bio/EnsEMBL/Production/Pipeline/StableID/sql/table.sql
The StableID pipeline inserts stable_id's into `stable_id_lookup` and creates indices, which is the correct approach.
However, 
- It creates indices considering the full lengths of VARCHAR fields, which can be large (255)
- It creates indices , which might be made redundant
The approach here is to reduce the lengths of some fields and avoid creating un-needed indices to make the pipeline more efficient.
The reduction proposal is based on considering the actual maximum length of the strings and adding a bit of contingency to it.
The index creation takes days in Ensembl main lifecycle.
Significantly speedup for index creation.
The changes might not be future proof, because of the "naive" shortening of the fields in the tables.
In case of longer stable IDs, the INSERT statements in …
=> StableID Pipeline - optimise index creation

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ChecksumGenerator_conf.pm
Incoporates the new genome factory into the checksum pipeline.
The checksum pipeline can be initialized against datasets which are in the submitted stage.
Can be used in our new set up.
Has not been tested in an old environment set up and may fail there.
Created a test dataset and the factory successfully processed the data.
=> ChecksumGenerator_conf.pm added support for genomefactory

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ChecksumLoader_conf.pm, src/python/ensembl/production/hive/ensembl_genome_metadata/ChecksumTransfer.py
Minor update to checksum loader pipeline. It was broken when the checksum generator pipeline was modified. Both should be fine now. 
Tested on 2000 genomes.
=> Removed conditional and fixed reference

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
A new attribute - GENCODE Primary - for Transcript has been added to `human`.
This attribute - as it will eventually replace GENCODE Basic - must be dumped into the annotation GTF/GFF3 files, as appropriate.
Although changes in the code are species-independent, the new attribute is used only for human.
The file dump pipelines must have the ability to add the new attribute, as appropriate.
Transcripts annotated as "GENCODE Primary" will be tagged as such in Ensembl GFF3/GTF files.
None
The test suite ran fine.
Dependencies
------------
These changes rely on Ensembl Perl API version 113 (new Transcript method to expose the new attribute, similarly to GENCODE Basic):
- ensembl: https://github.com/Ensembl/ensembl/pull/694
- ensembl-io: https://github.com/Ensembl/ensembl-io/pull/159
=> Added handling of new Transcript attribute 'gencode_primary'

nextflow/nf-py-scripts/generate_track_api_csv.py
Script to generate csv file for  track api loading  
MVP processing
Integrate into nextflow pipeline 
Fetch the metadata from metadata database and write it to CSV file 
Added to nextflow python script path to make it available for nf pipelines
=> script to generate csv file for track api dat load

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
"GENCODE Primary" tag should be `gencode_primary` also for consistency with E!112
Patching the string to comply with the agreed standard: `gencode_primary`
Keep the format consistent since day 1
None
N/A - patched the string only.
Dependencies
------------
None
=> Fixed gencode_primary string

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
GENCODE Primary tag must be considered in E!112 files (applicable to human).
Patching the string to comply with the agreed standard: `gencode_primary`
Keep the format consistent since day 1
None
N/A - patched the string only.
Dependencies
------------
None
=> Patched gencode_primary tag for harmonisation purposes

modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm, modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
Changing the "GENCODE Basic" tag (`basic`) to `gencode_basic` for harmonising it to GENCODE Primary and improved readability.
Sister PR to #918 - this one against `main`
Changing the "GENCODE Basic" tag (`basic`) to `gencode_basic` for harmonising it to GENCODE Primary and improved readability, as per ENSINT-1885.
Changing the "GENCODE Basic" tag (`basic`) to `gencode_basic` for harmonising it to GENCODE Primary and improved readability.
Potentially breaking downstream parsers
N/A
Dependencies
------------
None
=> Changed GENCODE Basic tag to 'gencode_basic'

nextflow/config/xref.config, nextflow/workflows/xrefDownload.nf, scripts/xrefs/cleanup_and_split_source.pl
Species files were being appended to even if not in update mode.
Under the scenario of a cleanup job failing, the …
=> Xref bugfix

modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
Prior to 113 the alphafold loading pipeline was setting analysis_description.display_label = "AlphaFold DB import" for alphafold. The website was expecting the value "AFDB-ENSP mapping", so links in the VEP results table were not being correctly displayed.
Make the web site happy again
None
Test suite completed successfully
Dependencies
------------
None
=> Fixed  as per ENSPROD-9493

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProcess_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Alignment.pm
Fixes for issues in 113 run.
The Alignment module wasn't handling errors in exonerate, leading to the job …
=> Xref fixes

modules/Bio/EnsEMBL/Production/Pipeline/Ga4ghChecksum/ChecksumGenerator.pm
There was an experimental Perl feature that allowed the use of a scalar containing a hashref in place of a hash, e.g. `keys $hashref`. That feature was deprecated, then removed in a recent update of Perl. This PR fixes such a use, converting the hashref to a hash for keys, e.g. `keys %{$hashref}`.
Changed in the live checkout and used to initialise a pipeline.
=> Fix use of keys on a scalar

modules/Bio/EnsEMBL/Production/Pipeline/GTF/DumpFile.pm
Related to https://github.com/Ensembl/ensembl-production/pull/918.
This PR updates the GTF header info to reflect recent changes to:
- `basic` to `gencode_basic`
- `primary` to `gencode_primary`
=> Update GENCODE tag info in header

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefDownload_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/gencode_sources.json, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_all_sources.json, modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json, src/python/ensembl/production/xrefs/config/xref_all_sources.json
-Updated analysis name from 'checksum_W' to 'checksum' in the XrefDownload configuration, since it didn't match the …
=> Minor bugfixes and updates for the XrefDownload pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
fix error :  Can't use string ("variation") as an ARRAY  in dbcopy pipeline
=> fix delete group param in dbcopy pipeline

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneTreeHighlighting_conf.pm
This PR addresses slow queries involving the `member_xref` table following the loading of GO and InterPro xrefs in …
=> Analyze and optimize after gene-tree highlighting

modules/Bio/EnsEMBL/Production/Pipeline/AttributeAnnotation/LoadAppris.pm
Noticed discrepancies regarding principle isoform scoring in appris data. According to the help 
documentation(https://appris.bioinfo.cnio.es/#/help/scores), principal isoforms are typically scored from 1 to 5. 
However, for some human entries, we observe a score of 0 for the "PRINCIPAL" designation and also for "ALTERNATIVE" isoforms, as seen in this example:
ENSG00000117501 ENST00000367759 PRINCIPAL:0
The resultant records  are manual overrides when  APPRIS is not picking up the correct coding transcript, these should be considered as scores with 1
=> set principle isoform score to 1

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/AlphaDBImport_conf.pm
The AFold pipeline fails init because of non-existing resource class (200M) in `datacheck` analysis.
Grabbed the minimum available (500M) to make it work.
Needed to instantiate the AFold pipeline, which turned out not being feasible.
Instantiate and run the pipeline.
Minimal suboptimal use of resources (RAM).
Manually and successfully instantiated the pipeline.
Dependencies
------------
Base_conf.pm in the same repo, which defines the available resource classes.
=> Fixed non-existing resource class

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ChecksumGenerator_conf.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ChecksumLoader_conf.pm, src/python/ensembl/production/hive/ensembl_genome_metadata/ChecksumTransfer.py
Fixed the checksum bulk updater to work with sqlalchemy 2.0
Improvements: Faster, no chance of error.
Drawbacks: Will overload the database if too many are ran at once. Concurrent jobs are set to one currently (200 genomes were tested and loaded sequentially in less than an hour)
Removed the params for hash_type in the metadata loader. We should always load both (don't look at who put it in originally) 
Tested and functional.
=> Fixed bulk update, removed hash type, put limit on concurrent jobs

scripts/copy_views.sh
Adds a standalone bash script that generates shell commands to copy MySQL views from one instance to another. 
We make frequent copies of the ensembl_genome_metadata database, but dbcopy doesn't copy views along with the tables. This script will find the views for a given database in a given MySQL instance and generate SQL commands to create those same views in a different instance and database. The SQL commands are wrapped in shell commands that use the MySQL aliases to facilitate connections to the source and target databases.
Hopefully simplifies the process of copying views to new databases.
The script doesn't try to actually run the shell commands, it just prints them out. This is because if the views have interdependencies then creating a view could fail unless its dependencies are …
=> Add new script to copy views from one MySQL DB to another

src/python/ensembl/production/xrefs/config/xref_all_sources.json
In 115, two xref source file locations have changed and have required updates. This is the duplicate PR to #995, where here the changes are for the `main` branch.
1. The FTP for ZFIN became inaccessible, leading to a new source file become required.
2. An updated file from Xenbase is available and should be used.
=> [main] Update xref_all_sources.json

src/python/ensembl/production/xrefs/config/xref_all_sources.json
In 115, two xref source file locations have changed and have required updates.
1. The FTP for ZFIN became inaccessible, leading to a new source file become required.
2. An updated file from Xenbase is available and should be used.
(I will create a duplicate PR against the `main` branch so this is included in future releases.)
=> [115] Update xref_all_sources.json

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpOrtholog_eg_conf.pm
This is a file Metazoa tends to forget it exists until something fails. For e115 _D. virilis_ was updated and we forgot to update it here, so its file is missing in `/nfs/ftp/public/databases/ensembl/projections/ensemblmetazoa` (we have a cron job that alerts us of this).
This PR fixes the issue, once the ortholog projection dump is generated.
_Note:_ I assume the files there are from e115, but let me know if these are still e114 and I will change the PR.
=> Update to metazoa species to latest assemblies

modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm, modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/LoadFamily_conf.pm
This PR would:
- add an extra check in `AddFamilyMembers` to require that `$gene_member->canonical_member_id` is …
=> Access canonical only if defined, allow more time

modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpVEP_conf.pm
From `release/114`, non-indexed vep cache directory is not supported via FTP dumps. This PR implements it through the VEP file dumping pipeline. It affects variation dumps for vertebrates and non-vertebrates.
=> Remove support for non-indexed vep folder
