Ensembl/ensembl-production

- scripts/datafiles/build_datafile_ftp_directory.pl
Faked DataFile objects. Added --schema_type option
Tested using --dry_run.
> Updated to work with funcgen ResultSets. 

- scripts/ontology/scripts/load_OBO_file.pl
Allows searching by synonym via the API.
Requires https://github.com/Ensembl/ensembl/pull/127
> store Ontology term synonym xref separately from name

- scripts/ontology/scripts/load_OBO_file.pl
We need to be able to track the versions of the ontologies used in each release. This updates the import script. 
Depends on https://github.com/Ensembl/ensembl/pull/132
> store version for ontology

- .travis.yml
- scripts/sql2html.pl
Just a few minor issues. Tested on compara's documentation
> Made sql2html's output pass the HTML validator

- scripts/ontology/scripts/load_OBO_file.pl
This pre-filters and creates a new file, as is already done for EFO.
> remove HPO lines which break parser before loading

- modules/Bio/EnsEMBL/Production/Pipeline/Chainfile/DumpFile.pm
cf https://github.com/Ensembl/ensembl/pull/184
> Do not skip first mapping when making chain file

- modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
also, all GOs are now mapped to transcripts rather than translations
> ENSCORESW-2087: upload GOs mapped to RNACentral ids

- modules/Bio/EnsEMBL/Production/Pipeline/EBeye/DumpFile.pm
- modules/Bio/EnsEMBL/Production/Pipeline/EBeye/DumpTypeFactory.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EBeye_conf.pm
…d default validator to xmllint
> EBeye updates e89

- modules/Bio/EnsEMBL/Production/Pipeline/Production/PepStats.pm
Following a suggestion from Dan S to fix an issue with genome loader.
> following advice from DS

- modules/Bio/EnsEMBL/Production/Pipeline/Ortholog/DumpFile.pm
genes with source INSDC will be labelled as coming from Ensembl
> assign ensembl source for MT genes

- scripts/datafiles/build_datafile_ftp_directory.pl
https://github.com/Ensembl/ensembl-production/pull/77#issuecomment-349023424
> Fix for the problem

- modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/CreateFamilies.pm
> MethodLinkSpeciesSet::species_set_obj is deprecated

- modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
- modules/t/test-genome-DBs/multi/production/meta.txt
- modules/t/test-genome-DBs/multi/production/table.sql
- sql/patch_92_93_a.sql
- sql/tables.sql
Schema patch_92_93_a_sql created and tables.sql updated.
Patch applied to test databases.
> Schema version 93 update

- scripts/ftp/checksums.pl
- scripts/sync/check_db.sh
- scripts/sync/check_public_db.sh
- scripts/sync/get_release.sh
- scripts/sync/get_staging_server.sh
- scripts/sync/process_divisions.sh
- scripts/sync/publish_db.sh
- scripts/sync/set_checksums.sh
- scripts/sync/sync_db.sh
- scripts/sync/sync_db_st1.sh
- scripts/sync/sync_db_st2.sh
- scripts/sync/update_live_db.sh
These are the scripts that are needed for publishing eg! databases and FTP dumps. They were under ensgen user but will be residing in ensembl-production repo from now on.
> New subdirectories for publication of eg! release

- .gitignore
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OntologyOLSLoadAll_conf.pm
Added new ontology 'mondo' to the default list.
> Added Mondo ontology to the default list

- modules/Bio/EnsEMBL/Production/Pipeline/Common/AnalysisSetup.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProjection_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProjection_mouse_strains_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneNamesProjection.pm
See JIRA ticket for details: https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-2124
> Xref projections fix null analysis

- .gitignore
- modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/CreateFamilies.pm
- modules/t/test-genome-DBs/multi/compara/table.sql
./patch_94_95_c.sql:DROP COLUMN is_high_coverage;
> Applied patch correlated with removal of a field in compara db for e95.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
To throttle some over-exuberant analyses, and take advantage of increased farm resources for the analyses doing the grunt work.
> Updating analysis/hive capactity for the Protein Features pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoadAll_conf.pm
Added PHI-Base EG ontology to the list of loaded ontologies
> Added 'PHI-Base' Ontology loading when loading all ontologies

- modules/Bio/EnsEMBL/Production/Pipeline/OntologiesLoad/MartLoad.pm
Fixed error in Building Ontology mart
> Removed exit line from MartLoad script

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Using DbFactory rather than SpeciesFactory to avoid redundant work and possibility of deadlocks for collection dbs. Also makes sense to move the datachecks to be after these modules complete.
The InterPro aggregating step at the end of the pipeline was being run once per species. For collection dbs this could cause a problem, because concurrent jobs could all be hitting the db at the same time. This is also not necessary, this information is db-level, so only needs to be added once.
Quicker execution, fewer concurrent db connections.
None I can think of.
No unit tests, but test pipeline run to completion.
> Improve performance of Protein Features pipeline

- .travis.yml
- cpanfile
- modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
- modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Extending Copy database module to deal with situation when we don't have file system access or if the database is …
> Copy service extend server support

- .travis.yml
- modules/t/test-genome-DBs/homo_sapiens/core/meta.txt
- modules/t/test-genome-DBs/homo_sapiens/core/table.sql
- modules/t/test-genome-DBs/multi/production/meta.txt
- modules/t/test-genome-DBs/multi/production/table.sql
- sql/patch_95_96_a.sql
- sql/table.sql
- travisci/harness.sh
Update production version to version 96 …
> update production db to version 96

- modules/t/test-genome-DBs/multi/production/master_biotype.txt
- sql/patch_96_97_b.sql
- sql/table.sql
This adds a new column (so_term) to the …
> so_term column to biotype table

- scripts/apply_patches.pl
Changed the processing of ontology database for new repo ols-ensembl-loader, …
> Updated link to ontology SQL patches files

- modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
We need to report error when running piped command, by default set -e will not report it and exit code will be 0... …
> Also checking for pipes errors

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoadAll_conf.pm
> Ontologies names now uppercase

- scripts/production_database/analysis_desc_from_prod.pl
> Cleaning up the script

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
> updated interproscan and packages within

- modules/Bio/EnsEMBL/Production/Pipeline/Common/AnalysisSetup.pm
> removing species dependency in production db

- scripts/ftp/upload_ena_xrefs.sh
Moving the ENA upload script from ensgen user space to the ensembl-production repo.
Not tested in the new location. …
> moved script over from ensgen user to production repo.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
_Correction in pipeconfig package name- package name and file name were different._
__
_NV searchdumps_
_._
Dependencies
------------
> Corrected pipeconfig for vert/non-vert searchdumps

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabase_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DBCopyPatch_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpGenomeJson_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpOrtholog_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EBeye_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FactoryTest_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FtpChecker_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/LoadFamily_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ReadQueues_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/UpdateComparaMemberNamesDescriptions_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProjection_mouse_strains_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Updating the EBI farm queue for all the Production modules as the new queue has much more capacity than the old …
> updating the farm queue

- modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
Typo: Wrong copy / paste from one test to another.
NA
NA
None
Dependencies
------------
> If applicable, define …
> Fixed typo in dataflow_output_id keys

- sql/patch_97_98_a.sql
BAU - Update patch
N/A
None
None
Dependencies
------------
> If applicable, define what code dependencies were …
> Updated meta table for release 98 version patch

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
Add dbname parameter to populate stable id script call. to remove versions from script.
Use good name for …
> Fixed db version failure

- modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Re-apply https://github.com/Ensembl/ensembl-production/pull/317 to release/97
see …
> Re-applied fix from release/98

- modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckComparaFtp.pm
We don't check for emf dumps at the moment
When checking compara dumps, we should check for emf dumps too.
We will …
> Added Compara emf dumps to the list

- sql/patch_98_99_a.sql
- sql/table.sql
Created schema patch for release 99 and updated table.sql
This is required when we start a new release and need to …
> Created schema patches for release 99

- modules/t/test-genome-DBs/homo_sapiens_dump/funcgen/meta.txt
- modules/t/test-genome-DBs/homo_sapiens_dump/funcgen/table.sql
Updating test databases to 99 schema
Needed before branching.
Test databases will be up to date with release 99 …
> Updated test databases to 99

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Updated Interproscan version to 76.0
_Describe the problem. Please provide an example representing the motivation …
> Updated Interproscan version to 76.0

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
We need to increased the required memory for some of out modules.
Normal use case.
Pipeline will run...
None
- [ N …
> Increased memory requirement for Xrefs and core statistics

- scripts/datafiles/build_datafile_ftp_directory.pl
No extrarequeriments needed
The code added will create the symlinks to the emission files located in the different segmentation folders for the Funcgen ftp. These files were not included in the data_file table of the database so they must be sync individually. 
There is one emission file for each segmentation. 
Emission files were not included in the data_file table of the database so they must be sync individually. 
There is one emission file for each segmentation. 
Emission files will be added to FTP folder
It has been tested locally.
Dependencies
------------
No dependencies
> add emission files to the build_datafile_ftp_directory.pl script

- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
copy of https://github.com/Ensembl/ensembl-production/pull/365 for release/100
_Describe the problem. Please provide an example representing the motivation behind the need for having these changes in place._
_If applicable, describe the advantages the changes will have._
_If applicable, describe any possible undesirable consequence of the changes._
Dependencies
------------
> [ENSCORESW-3347] update JGI data source [release/100]

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Update Update interproscan version to 5.39-77.0 in ProteinFeatures_conf.pm
Using Update interproscan version to …
> Update interproscan version to 5.39-77.0

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Memory increase so that pipeline don't die.
When running it for the release.
We can run the pipeline next release …
> Increating memory for the large queue

- modules/Bio/EnsEMBL/Production/Pipeline/Common/AnalysisSetup.pm
- modules/Bio/EnsEMBL/Production/Pipeline/GeneAutocomplete/CreateGeneAutoComplete.pm
Minor changes to accommodate JSON-format web_data.
https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-4752
This should only be merged once we have swtiched the production db to use JSON format, and propagated the web_data to the core dbs.
> Minor changes to accommodate JSON-format web_data.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Dog got renamed in release 100, so we need to update this species check for BLAT: …
> Renamed Dog

- scripts/datafiles/build_datafile_ftp_directory.pl
Motif and dna-methy datafiles are missing in ftp release directory. Fixed by adding two adaptors DNAMethylationFileAdaptor and MotifFeatureFileAdaptor.
> Incomplete data file funcgen ensprod 4849

- modules/Bio/EnsEMBL/Production/Search/EBeyeFormatter.pm
- modules/t/ebeye_sequences_test.xml.expected
- modules/t/ebeye_variants_test.xml.expected
Add system_name field for sequence/variant search XML 
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4973
EBEye search needs system_name field in sequence/variant XML for searching sequence/variant from species home page.
Dependencies
------------
None
> Add system_name field for sequence/variant search XML

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/UpdateComparaMemberNamesDescriptions_conf.pm
When running the pipeline on pan compara, …
> Pan compara needs more memory

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Business-as-usual update for InterProScan. (Done earlier then we need, at request of VectorBase, who want to run the ProteinFeatures pipeline.)
> Update to latest InterProScan version

- sql/patch_100_101_a.sql
- sql/patch_99_100_a.sql
- sql/table.sql
Release 100 and 101 schema patches
Getting patches ready for release 101.
_If applicable, describe the advantages …
> Added schema patches for release 100 and 101

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SampleData_non_vertebrates_conf.pm
As requested by @thomasmaurel me and @gnaamati have added plant species to the antispecies list at 
modules/Bio/EnsEMBL/Production/Pipeline/PipeConfigSampleData_non_vertebrates_conf.pm
These plants should not be added sample genes automatically.
> added plants to antispecies list

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SampleData_non_vertebrates_conf.pm
Adding cucumis_melo as requested by Plants …
> Adding cucumis_melo

- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Bug fix in the data source for MIM2Gene data. Parser for 101 uses a slightly different input file.
Xref for human …
> Bug-fix in data source for MIM2Gene.

- modules/Bio/EnsEMBL/Production/Search/VariantAdvancedSearchFormatter.pm
Module loose connection to the ontology database after few hours. Manually disconnecting fix the issue.
When …
> Fixing module loosing connection to the ontology db

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Update InterProScan Version to 5.42.78
> updated interproscan version

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Datacheck type Xref  added to Xref Pipeline
> Add xref datacheck to pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Needs to go back to earlier data source. Does not affect the xref data
for human.
This reverts commit 6256e62b780bea54013fe00c9b8e059f21bf0a71.
As discussed in production meeting, reverting the changes. Production to merge it with master.
> Revert "Bug-fix in data source for MIM2Gene."

- modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
This piece of code shouldn't be here, sounds like a test not removed upon commit, or a merge which went wrong. …
> Remove "Test like" piece of code

- modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
- modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
Fix missing Try / Catch missing package error
Package Try/Catch not present.
Fix package
None
Dependencies
------------
> Fix usage of Try / Catch

- modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
- modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm
- modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckVariationFtp.pm
- modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpGenesJson.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpGenomeJson.pm
- scripts/datafiles/build_datafile_ftp_directory.pl
- scripts/datafiles/check_datafiles.pl
- scripts/datafiles/sizes.pl
Same as #430 but on `release/101`
> [ENSCOMPARASW-3527] Allow division-prefixed Ancestral sequences Registry entries

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
Same as #435, on release/102 branch rather than master.
> Add biotype datacheck to prod db sync pipeline.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
> Update interproscan version, which includes a new Pfam release.

- modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
Code was adding source xrefs for almost all GO xrefs - but was relying on an assumption about accessions being unique to a particular source. This is not the case, e.g. PRIDE uses the UniProt accessions, which was leading to a bug the annotation of a metazoan species.
See https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-5474 for a detailed breakdown.
More accurate GO xref annotation. GOXrefEvidence datacheck will not fail.
None I can think of
No unit tests, but GPAD Load pipeline was successfully run for formerly problematic metazoan species.
> Ensure GO xrefs have a source xref

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Updating datacheck group for xref pipeline so that only datachecks relevant to this pipeline are run.
> Updating datacheck group for xref pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/LoadFamily/AddFamilyMembers.pm
Gene stable IDs shouldn't, ideally, be duplicated in different species. But it happens, so we should dealt with it as gracefully as possible. Trying to save a duplicate in the compara db causes a fatal error, and processing of the species is aborted. In this update, the error is trapped and logged, but processing of other genes, with non-duplicated stable IDs, can continue.
Gene family pipeline is as complete as possible.
None I can think of.
No unit tests, but tested by running the pipeline on databases with duplicated stable IDs.
> Handle duplicate stable IDs in gene family pipeline

- modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
CDS data added to search dumps (ENSPROD-5397)
initialise translation key  for all non-coding genes in  search dumps  (ENSPROD-5872)
> cds data added to search dumps; translation key added to search dumps

- modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
PR : alread raised against the release 102
CDS data added to search dumps (ENSPROD-5397)
initialise translation key for all non-coding genes in search dumps (ENSPROD-5872)
> Add cds to search dumps

- modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Replicating #485 on release/103
> Don't remove \r characters from dumps

- modules/t/11-searchdumps_dumpgenes.t
Added cds data to example gene to avoid  build script to fail .
> added cds data to example gene

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
> Update interproscan version 5.46-81.0

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneAutoComplete_conf.pm
If left unspecified, it'll run 100s of concurrent jobs against the server...
Also tidied up whitespace.
> Add analysis_capacity for the gene autocomplete analysis

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Added new port number for BLAT indexes following updates on related assembly
WEB tools files dumps for new release
obvious?
None
Dependencies
------------
> Updated port number for new / updated species assembly.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpSpeciesForGOA_conf.pm
Change SpeciesFactory parameter defaults from empty strings to empty lists, to ensure that lists of species are correctly handled.
Set the default output location to be the one used by GOA, to avoid typos or omissions in the parameter initialisation that lead to the data being saved elsewhere.
Replaced the over-engineered code for the 'release.txt' file with a unix one-liner.
Pipeline initialised and successfully run with new config.
(This is a duplicate of #503, because I made a mess of the rebasing to release/103 - I think it needs to be on the branch, so that we don't need to switch to master for this pipeline when processing the next few RR releases.)
> Config file for Rapid Release dumps for GOA

- modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
Replicating #512 on latest release branch.
> Add explicit disconnects in variant json dumps

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneTreeHighlighting_conf.pm
The external_db data was being loaded from the master version of the table in the production database, which has a different schema to that of the compara db; which works because the former is a superset of the latter, but now we are testing the compara schema with a datacheck (https://github.com/Ensembl/ensembl-datacheck/pull/324) we don't want to do that anymore, because the datacheck will fail.
Loading the whole table from the prod db is more than is necessary; only two rows are needed, and these are essentially static, so we can save ourselves some complexity and hard-code them in the conf file.
Schema-related datacheck will not fail for compara dbs.
Pipeline initialised and executed first job successfully.
> Update how the external_db is populated by Gene Highlighting pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
Stable IDs is missing some species due to parallel call to script
StableIds generation
No more missing species. 
Pipeline longer to run.
Dependencies
------------
> reduce analysis capacity to remove parallel script calls

- sql/patch_103_104_a.sql
Added sql patch
NTR
_If applicable, describe the advantages the changes will have._
_If applicable, describe any possible undesirable consequence of the changes._
Dependencies
------------
> added 104 sql patch

- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/GeneAndTranscript.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/ChromReport.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/CoordinateConverter.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/Genome.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/GenomeLookup.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/GenomeReport.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/IndexBed.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/IndexWig.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/variants/VariantsScaler.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/variants/VariationBedWriter.pm
added license to webdatafile modules
> added license to lib module for webdatafile pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Updated interproscan and its models version
> Update interproscan version

- scripts/py/meta_hive_species.py
Script nos generate those files (or v param instead of ENS_VERSION)
- database_{ENS_VERSION}.txt -> List of params -database xxx
- dblist_{ENS_VERSION}.txt -> List of databases comma separated
- species_{ENS_VERSION}.txt -> List of -species xxx
Update the script to generated expected params for db copy client
DB copies for RR - copy only released DB
Only copy necessary dbs
Missing related of and variation. We'll see after RR15 what's next and to reuse script from @radome 
Dependencies
------------
> Update script to dump three files into HOME:

- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Exists.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/AnalysisConfiguration.pm
Two small fixes for Rapid Release pipelines.
> Small fixes for Rapid Release pipelines

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpVariation_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ReadQueues_conf.pm
Reverts Ensembl/ensembl-production#543
Return to user setup instead of mailing list.
> Revert "Updated default mail to ensembl-production@ebi.ac.uk where necessary/…"

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/RNAGeneXref_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/RNAGeneXref/AnalysisConfiguration.pm
- modules/Bio/EnsEMBL/Production/Pipeline/RNAGeneXref/LoadRNACentral.pm
- modules/Bio/EnsEMBL/Production/Pipeline/RNAGeneXref/RNACentralXref.pm
> Fix 2021 copyright tags that weren't updated

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
> Add antispecies & high memory analyses to ProductionDBSync_conf

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Updated port number for new assembly meleagris_gallopavo in `DumpCore_conf.pm`
> Updated port number for new assembly meleagris_gallopavo

- modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
- modules/Bio/EnsEMBL/Production/Pipeline/MirrorLoad/DeleteDBs.pm
- modules/Bio/EnsEMBL/Production/Pipeline/MirrorLoad/ListDatabase.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MirrorLoad_conf.pm
Business-as-usual merge of release 104 fixes onto master.
> Merge release/104 fixes onto master

- modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
These changes were implemented on the 'ensprod' local checkout.
They appear to increase the robustness of the code, but not exactly sure of the background.
> Increase robustness of CopyDatabase

- modules/Bio/EnsEMBL/Production/Pipeline/OntologiesLoad/MartLoad.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoadAll_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Modified pipeline conf file according to new codon server
> Codon migrations

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
When testing the parameterisation of the Ontology Load pipeline on Codon, in order to update the SOP, I noticed that the datachecks are almost guaranteed to fail. The comparison with the previous release will usually throw up something, but will rarely be anything to worry about. If that test is critical, the pipeline will generally fail, and not create the dbcopy jobs.
Split the datacheck execution into advisory and critical sets; the comparison check is made advisory (cf https://github.com/Ensembl/ensembl-datacheck/pull/385), and the report is emailed.
Renamed a couple of variables and reformatted a bit, to be consistent with other pipelines.
Pipeline won't always fail.
If there _is_ a significant drop in the terms between releases, then we rely on someone paying attention to emails. An …
> Ontology Load pipeline updates

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpMySQL_conf.pm
Forgot to include this in the #575 PR: accept multiple `-dbname` parameters, to dump arbitrary databases.
Test pipeline successfully executed.
> Add ability to dump a named database.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
At least now we've rationalised things, only need to update in one place!
> Updated path for scratch dir

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_plants_conf.pm
Change parameter names to `antispecies`
> Exclude outgroup species

- .travis.yml
- sql/patch_105_106_a.sql
Forgot to patch the meta table.
> Added patched version sql

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
#599 backported to release/105.
> Pass division parameter to rename factory

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_conf.pm
Backport of #603 to release/105 branch.
> Bugfix/search dump config (105)

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
Advisroy Datachecks are reported per DC failure via email  which will be too many per pipeline.  We wanted to combine all the failed advisory dc and report them together via single email.  To achive this we used  existing DC module to collect the all the tap formated dc results  files created during datacheck run and convert them to json file using ConvertTapToJson module and send this json file via email which contain only failed advisory dc.
New Module 'AdvisoryDataCheckSummary' created to report all failed advisory dc together. : https://github.com/Ensembl/ensembl-datacheck/pull/416
Implemented this new feature into GPAD pipeline.
> collective advisory dc reports implemeted to GPAD pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
We observed no ontology terms are missing when analysis capacity set to 1
> Set analysis capacity to 1

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
- src/python/ensembl/production/hive/FileWatcher.py
Filewatcher hive module for release/105 used for rapid release
> filewatcher hive module for release/105

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
https://github.com/Ensembl/ensembl-datacheck/pull/431
> Renamed AdvisoryDataCheckReport to DataCheckMailSummary

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
Added more default to use in subsequent pipelines.
More generic params to be used across our pipelines. 
Less to defined in subclasses.
None
Dependencies
------------
> updated some default for upcoming Xref new pipeline(s)

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
- src/python/ensembl/production/hive/ProductionDBCopy.py
Related to #636 and handling changes introduced in https://github.com/Ensembl/ensembl-prodinf-dbcopy/pull/24/commits/515c6279bce3b7ca0481fddf2c255d027715a805
> Handle case where DBCopy endpoint returns job_id as a list

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
> Update email parameter

- modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
- modules/t/11-searchdumps_dumpgenes.t
Added exon phase more details in ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-5803
> Ensprod 5803 exon phase

- modules/Bio/EnsEMBL/Production/Pipeline/Common/MetadataDbFactory.pm
Hot fix for DBCopy config
Setup databases for stagings.
No more bug
None
Dependencies
------------
> Fixed error in query extra params construction.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Path were still pointing to old FTP structure from noah. 
Copy from previous release step  failures in 107 run.
No more failures :-) 
Pipeline may be slower due to number of concurrent job limitation on DM queues. 
Dependencies
------------
> Updated path to expected new dirs on CODON.

- modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TaxonomyInfoCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/TaxonomyUpdate/QueryMetadata.pm
Updated pipeline to handle collection db and update meta table for given species.
Added new flag to DBFactory to through db not found error  
more details in ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7393
> pipeline compatible to update collection dbs

- .travis.yml
- modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
Update typo in GPAD LoadFile job
> update typo in GPAD LoadFile job

- modules/Bio/EnsEMBL/Production/Pipeline/JSON/genes_schema.json
New flag canonical added gene schema for json dumps
> canonical flag added to json dump

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabaseDBA_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Update DBCopy url following migration to HL
DBCopy pipeline.
DBcopy don't fail
None. 
Dependencies
------------
> Updated DBCopy default target api url.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Reformat file.
Change rsync queues for Codon.
RR FTP dumps 
No need to update manually the pipeline for failures.
None. 
Dependencies
------------
> Report fix applied on 106

- scripts/assembly_converter/populate_assembly_converter_dir.sh
default ftp path updated for assembly converter script
> default pub ftp paths changed as per codon

- modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
unable to find genome xml  recursively , cmd command find will do the needful work
> File::Find::Rule unable to find genome xml

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/LoadAppris_conf.pm
Updated new DC to check more thoroughly the match between loaded file content and imported data. 
APPRIS load sometime do not load expected content, added a new DC to check that imported data counts match the loaded file content
Better warnings when running APPRIS load
None
Currently testing on sample datasets. Done on Mus_musculus 107 datasets, worked well, then reduce data in transcrib attrib, and expected failure happened. 
Dependencies
------------
> Added new DC to APPRIS load

- scripts/datafiles/build_datafile_ftp_directory.pl
Remove data_files linking from FTP dirs for regulation. 
No more useless symlinkings
None
Dependencies
------------
> Removed funcgen specific processing from script.

- scripts/py/alphafoldUpdate_parallel.py
New version for the `alphafoldUpdate` script: this is leveraging on ProcessPoolExecutor for parallel execution
Same as existing `alphafoldUpdate` script.
Enhanced performance
None
Manually done and successfully executed.
> Added new alphafold script version

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Datacheck output creating duplicate jobs in the speciesfactory with resulted running jobs multiple times and failing to meet desired inputs.
details are in ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7770
> fix for recurring error

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefDownload_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProcess_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/AdvisoryXrefReport.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/EmailAdvisoryXrefReport.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/EmailNotification.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/RefSeqDatabaseParser.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleSource.pm
Xref pipeline fixes and changes:
- Bug fix: duplicate variable $preparse declaration
- Fixed the way we set the …
> Xref changes: RefSeq fix + DC and pipeline emails fixes

- src/python/ensembl/production/hive/ProductionDBCopy.py
Replaced HiveREST client with production dbcopy client
> replaced standard hiveRest client with production dbcopy client

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Production/GeneCount.pm
New flag added to include or exclude readthrough gene count 
More info  in jira ticket : https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7999
> added flag to include or exclude readthrough gene count

- .travis.yml
- modules/Bio/EnsEMBL/Production/Search/JSONReformatter.pm
- modules/t/11-searchdumps_dumpgenes.t
- modules/t/test-genome-DBs/homo_sapiens/core/transcript_attrib.txt
- modules/t/test-genome-DBs/hp_dump/core/transcript_attrib.txt
Added 5.26 to PERL build 
Expected upgrade to PERL 5.26
Code testing works with 5.26
TBD
Dependencies
------------
> Features/perl 5.26

- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm
- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/DirectoryPaths.pm
- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Symlink.pm
- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Symlink_RNASeq.pm
> Feature/new sub directory  from  metakey annotation_source

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefDownload_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Base.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/DownloadSource.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/UniProtDatabaseParser.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleDownload.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/gencode_sources.json
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_all_sources.json
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Recently, some xref source files have been corrupted or incomplete which is leading to job failures. This prompted …
> Xref download changes

- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.pm
- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.txt
- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Symlink.pm
Updated README.pm and README.txt accordingly.
Missed directories structure tests for symlinking.
Update README.txt and README.pm to handle new file types available on FTP.
Included declaration of annotation.source subdirectories in README.txt
RR FTP dumps
README inline with content
None
Dependencies
------------
> Further updates following new FTP layout and subdirectories

- sql/patch_108_109_a.sql
Added patch to 109 schema
Release db
N/A
None
Dependencies
------------
> Added schema patch for 109

- scripts/assembly_converter/populate_assembly_converter_dir.sh
See https://github.com/Ensembl/ensembl-production/pull/757 
https://github.com/Ensembl/ensembl-production/pull/757
_If applicable, describe the advantages the changes will have._
_If applicable, describe any possible undesirable consequence of the changes._
Dependencies
------------
> Report from PR against 109: 

- scripts/assembly_converter/populate_assembly_converter_dir.sh
- single source of data for a release --> simplified script
- added options
- changed paths
Tools files handover to web. 
Simpler script
WEB SOP need changing to keep `www` dir name for verts
Dependencies
------------
> Updates in assembly-converter

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DataFileScanner_conf.pm
- src/python/ensembl/production/datafile/scraper/serializers.py
- src/python/ensembl/production/hive/DataFileScanner.py
New pipeline to support the DataFile API work for scanning directories and creating relevant MANIFEST files.
This …
> DataFile Scanner Pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Integrate Homology dump steps into RR ftp dump pipeline
Can run homoly dumps alone for any given division or species
> integrate homology dump steps into rr ftp pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabaseDBA_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EarlyDumps_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
set new service url for dbcopy api
> Update new service url

- modules/Bio/EnsEMBL/Production/Pipeline/Common/Gzip.pm
Added simple array check for gzip
Fixes error introduced with gzip when mysql passes a string
Tested and works.
> Added Gzip check for array

- scripts/py/regulation_ftp_symlinks.py
Fix `data_files` path removing `vertebrates` folder
> fix data_files path removig the vertebrates folder

- scripts/py/regulation_ftp_symlinks.py
Point symlink to the analysis_type folder and not to the release folder.
> Fix symlink path

- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/gencode_sources.json
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_all_sources.json
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
This PR updates the URL for downloading the …
> Updated download URL for miRBase miRNA.dat file

- .gitignore
- sql/patch_111_112_a.sql
Forgot patch files for 112 branching
Release branching
None
None
Dependencies
------------
> Updated .gitignore + patch DQ forgotten when initially branching

- modules/Bio/EnsEMBL/Production/Pipeline/Common/Gzip.pm
- modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpMySQL_conf.pm
- modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFile.pm
- modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm
- modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileMetadata.pm
- modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
Missing Gzip fixes from release/111 branch
Gzip issues and jobs hanging forever while dumping fixes
Pipeline faster / more reliable
Any missed part from origin PR from origin branch bugfix/gzip
Dependencies
------------
> Retrieve source from lost PR about Gzip fixes

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
Part of the resource class SLURM updates. Here are the updates for core_stats
Running core stats hive with SLURM
Fully tested
> Updated Core stats resources.

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Update blat port for bos_taurus
> Update blat port for species bos_taurus

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
update blat port for species bos_taururs
> update port for blat files

- modules/Bio/EnsEMBL/Production/Pipeline/Common/Gzip.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Same as PR https://github.com/Ensembl/ensembl-production/pull/852
> Added gzip module and converted FileDump_conf.pm to perl gzip module

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EarlyDumps_conf.pm
removed analysis step copytopublicftp
> removed analysis step copytopublicftp

- modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
Integrate access to GIFTS data into the pipeline. The GIFTS DB is now queried directly for species where GIFTS data is available.
Easier SOP for production.
DBD::Pg module needed, DB must be online
Changes were tested for one species.
Removed Bio::EnsEMBL::GIFTS::DB
Added DBD::Pg
> Integrate GIFTS

- modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/AlphaDBImport_conf.pm
Just putting https://github.com/Ensembl/ensembl-production/pull/859
onto 112 branch from main
> alphafold updates to 112

- scripts/py/regulation_ftp_symlinks.py
[BIGFIX] - Fix `signal` symlink in rf dir
> fix signals symlink in rf dir

- modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/CreateAlphaDB.pm
- modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/CreateUniparcDB.pm
- modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/AlphaDBImport_conf.pm
- Pieline ran cleanup too early, after the first datacheck finished. Fixed.
- Removed a few newlines that we were storing but don't need
> Rework alphafold pipeline cleanup logic

- requirements.in
- requirements.txt
- src/python/ensembl/production/factories/metadata/genomeFactory.py
GenomeFactory 
Fetch genome by dataset  status 
updates the dataset status
batch limit set with default value 50
> updates to new genome factory

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
Simple Bug fix to properly get memory specification. 
Tested.
> Fixed array bug

- nextflow/config/thoas.config
- nextflow/modules/productionCommon.nf
- nextflow/modules/thoasCommonProcess.nf
- nextflow/nf-py-scripts/generate_thoas_conf.py
- nextflow/nf-py-scripts/genome_info.py
- nextflow/nf-py-scripts/thoas_load.py
- nextflow/workflows/thoasloading.nf
Changes required for Thoas NF Pipeline  compatible for new GenomeFactory and  new Mongo DB Schema (https://github.com/Ensembl/ensembl-core-mongodb-loading/pull/24)
> Thoas NF Pipeline Changes for New Mongo Schema

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EnsemblHomologyAnnotation_conf.pm
Genome Factory Integration For Homology Annotation Pipeline 
Changes required in compara repo : https://github.com/Ensembl/ensembl-compara/pull/758
> genome factory integration for homology pipeline

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
GenomeFactory in PF pipeline
MVP processing
Factory in place
None
Dependencies
------------
> Integrate Factory in PF pipeline

- sql/patch_110_111_a.sql
- sql/patch_112_113_a.sql
- sql/table.sql
Just the updates for the patches to prepare for release/113
> Updated patches for preperation of 113

- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ScheduleSource.pm
- scripts/xrefs/cleanup_and_split_source.pl
- src/python/ensembl/xrefs/Base.py
- src/python/ensembl/xrefs/EmailNotification.py
Some minor fixes and additions into new xref download pipeline.
Added fixes for some minor issues discovered in …
> Minor fixes

- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/gencode_sources.json
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_all_sources.json
- modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
This is an update to the HGNC custom …
> Updated HGNC custom download URL

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
Simple update to increase memory for default in all pipelines. 100mb=>1GB
> Updated default resources from 100mb to 1gb

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
Increase memory to 1G for default resource class
> slurm_default_resource_class

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
Update Base default resource to 1GB memory
> Update base default resource to 1GB memory

- scripts/py/regulation_ftp_symlinks.py
Include Human and Mouse in the set of species to be symlinked in FTP.
> Include human and mouse in the Regulation FTP symlink approach.

- modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm
> Updated paramaters for mvp

- scripts/ftp/checksums.pl
Updated perl checksum script to only output filenames
> Update checksums with basename

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
> RC Update ProductionDBSync_conf.pm

- scripts/copy_views.sh
Updates the end year in the copyright notice.
> Update copyright year

- nextflow/nf-py-scripts/track_api_loading.py
Add track api loading script. 
[ENSPROD-10114](https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-10114)
_If …
> Track api loading

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Fix Hive GUI Load Issue For FTPDUMP Pipeline 
hive db : ens2020_ftp_dumps_beta6_test_gui_1 in h1
> Fix file dumps

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
> RC change GPAD_conf.pm

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Stopped the throttling of the pipeline from a few hive capacity values set to 10.
Replaced these with analysis capacity in these cases.
Removed the batch processing as there is an intrinsic bug to it in hive.
Removed the non-slurm resource classes.
Not tested, but should be fine.
> DumpCore_conf resource class optimization

- scripts/py/regulation_ftp_symlinks.py
> Fix release search

- modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpOrtholog_eg_conf.pm
Update the list of species following the updates planned for e116 (and add one missing update from e115, reported as a known bug).
> [Metazoa] Update list of orthologues to dump with latest species updates for e116
